// Code generated by goxogen. DO NOT EDIT.
package goxus

import (
	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
	"github.com/nobuenhombre/suikat/pkg/db/types"
	"github.com/nobuenhombre/suikat/pkg/ge"
)

type DbGoxusRepo struct {
	db                 pgxdb.DBQuery
	RbacPermission     IRbacPermissionRepository
	RbacRole           IRbacRoleRepository
	RbacRolePermission IRbacRolePermissionRepository
	RbacUserRole       IRbacUserRoleRepository
	SchemaMigration    ISchemaMigrationRepository
	User               IUserRepository
	UsersToken         IUsersTokenRepository
	UserWithRole       IUserWithRoleRepository
}

func NewDbGoxusRepository(config *pgxdb.Config, log types.SQLLoggerFunc) (*DbGoxusRepo, error) {
	db, err := pgxdb.New(config, log)
	if err != nil {
		return nil, ge.Pin(err)
	}

	return &DbGoxusRepo{
		db:                 db,
		RbacPermission:     NewRbacPermissionRepository(db),
		RbacRole:           NewRbacRoleRepository(db),
		RbacRolePermission: NewRbacRolePermissionRepository(db),
		RbacUserRole:       NewRbacUserRoleRepository(db),
		SchemaMigration:    NewSchemaMigrationRepository(db),
		User:               NewUserRepository(db),
		UsersToken:         NewUsersTokenRepository(db),
		UserWithRole:       NewUserWithRoleRepository(db),
	}, nil
}

// Close closes the database connection.
func (dbRepo *DbGoxusRepo) Close() {
	dbRepo.db.Close()
}
