// Code generated by goxogen. DO NOT EDIT.
package goxus

import (
	"github.com/google/wire"
	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
	"github.com/nobuenhombre/suikat/pkg/db/types"
	"github.com/nobuenhombre/suikat/pkg/ge"
)

// ProviderSet exports Wire providers for the generated package.
var ProviderSet = wire.NewSet(
	ProviderGoxus,
)

// ProviderGoxus creates a DbGoxusRepo and returns it with a cleanup function.
func ProviderGoxus(config *pgxdb.Config, log types.SQLLoggerFunc) (*DbGoxusRepo, func(), error) {
	dbRepo, err := NewDbGoxusRepository(config, log)
	if err != nil {
		return nil, nil, ge.Pin(err)
	}

	cleanup := func() {
		dbRepo.Close()
	}

	return dbRepo, cleanup, nil
}
