// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"errors"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// RbacUserRole represents a row from 'public.rbac_user_roles'.
type RbacUserRole struct {
	ID        int64     `json:"id"`         // id
	UserID    int64     `json:"user_id"`    // user_id
	RoleID    int64     `json:"role_id"`    // role_id
	CreatedAt time.Time `json:"created_at"` // created_at
	UpdatedAt time.Time `json:"updated_at"` // updated_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the RbacUserRole exists in the database.
func (rur *RbacUserRole) Exists() bool {
	return rur._exists
}

// SetExists determines if the RbacUserRole exists in the database.
func (rur *RbacUserRole) SetExists(exists bool) {
	rur._exists = exists
}

// Deleted provides information if the RbacUserRole has been deleted from the database.
func (rur *RbacUserRole) Deleted() bool {
	return rur._deleted
}

// Insert inserts the RbacUserRole to the database.
func (rur *RbacUserRole) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if rur._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.rbac_user_roles (
user_id, role_id, created_at, updated_at
) VALUES (
$1, $2, $3, $4
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, rur.UserID, rur.RoleID, rur.CreatedAt, rur.UpdatedAt).Scan(&rur.ID)

	db.WriteLog(sqlstr, time.Since(start), rur.UserID, rur.RoleID, rur.CreatedAt, rur.UpdatedAt)

	if err != nil {
		return err
	}

	// set existence
	rur._exists = true

	return nil
}

// Update updates the RbacUserRole in the database.
func (rur *RbacUserRole) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !rur._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if rur._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.rbac_user_roles SET (
user_id, role_id, created_at, updated_at
) = (
$1, $2, $3, $4
) WHERE id = $5
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rur.UserID, rur.RoleID, rur.CreatedAt, rur.UpdatedAt, rur.ID)

	db.WriteLog(sqlstr, time.Since(start), rur.UserID, rur.RoleID, rur.CreatedAt, rur.UpdatedAt, rur.ID)

	return err
}

// Save saves the RbacUserRole to the database.
func (rur *RbacUserRole) Save(db pgxdb.DBQuery) error {
	if rur.Exists() {
		return rur.Update(db)
	}

	return rur.Insert(db)
}

// Upsert performs an upsert for RbacUserRole.
//
// NOTE: PostgreSQL 9.5+ only
func (rur *RbacUserRole) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if rur._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.rbac_user_roles (
id, user_id, role_id, created_at, updated_at
) VALUES (
$1, $2, $3, $4, $5
) ON CONFLICT (id) DO UPDATE SET (
id, user_id, role_id, created_at, updated_at
) = (
EXCLUDED.id, EXCLUDED.user_id, EXCLUDED.role_id, EXCLUDED.created_at, EXCLUDED.updated_at
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rur.ID, rur.UserID, rur.RoleID, rur.CreatedAt, rur.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), rur.ID, rur.UserID, rur.RoleID, rur.CreatedAt, rur.UpdatedAt)

	if err != nil {
		return err
	}

	// set existence
	rur._exists = true

	return nil
}

// Delete deletes the RbacUserRole from the database.
func (rur *RbacUserRole) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !rur._exists {
		return nil
	}

	// if deleted, bail
	if rur._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.rbac_user_roles
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rur.ID)

	db.WriteLog(sqlstr, time.Since(start), rur.ID)

	if err != nil {
		return err
	}

	// set deleted
	rur._deleted = true

	return nil
}

// GetAllRbacUserRole returns all rows from 'public.rbac_user_roles',
func GetAllRbacUserRole(db pgxdb.DBQuery) ([]*RbacUserRole, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, user_id, role_id, created_at, updated_at
FROM public.rbac_user_roles
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacUserRole
	for q.Next() {
		rur := RbacUserRole{}

		// scan
		err = q.Scan(&rur.ID, &rur.UserID, &rur.RoleID, &rur.CreatedAt, &rur.UpdatedAt)
		if err != nil {
			return nil, err
		}
		rur.SetExists(true)

		res = append(res, &rur)
	}

	return res, nil
}

// GetRbacUserRolesBySQL returns rows from 'public.rbac_user_roles' by your SQL,
func GetRbacUserRolesBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*RbacUserRole, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacUserRole
	for q.Next() {
		rur := RbacUserRole{}

		// scan
		err = q.Scan(&rur.ID, &rur.UserID, &rur.RoleID, &rur.CreatedAt, &rur.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &rur)
	}

	return res, nil
}

// GetLastRbacUserRole returns last row from 'public.rbac_user_roles',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDRbacUserRole(db pgxdb.DBQuery) (*RbacUserRole, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, user_id, role_id, created_at, updated_at
FROM public.rbac_user_roles
ORDER BY
id DESC
LIMIT 1
`

	var rur RbacUserRole
	err := db.QueryRow(ctx, sqlstr).Scan(&rur.ID, &rur.UserID, &rur.RoleID, &rur.CreatedAt, &rur.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	rur._exists = true
	rur._deleted = false

	return &rur, nil
}

// RbacRole returns the RbacRole associated with the RbacUserRole's RoleID (role_id).
//
// Generated from foreign key 'rbac_user_roles_roles_fk'.
func (rur *RbacUserRole) GetRbacRole(db pgxdb.DBQuery) (*RbacRole, error) {
	return GetRbacRoleByID(db, rur.RoleID)
}

// User returns the User associated with the RbacUserRole's UserID (user_id).
//
// Generated from foreign key 'rbac_user_roles_users_fk'.
func (rur *RbacUserRole) GetUser(db pgxdb.DBQuery) (*User, error) {
	return GetUserByID(db, rur.UserID)
}

// RbacUserRoleByID retrieves a row from 'public.rbac_user_roles' as a RbacUserRole.
//
// Generated from index 'rbac_user_roles_pk'.
func GetRbacUserRoleByID(db pgxdb.DBQuery, id int64) (*RbacUserRole, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, user_id, role_id, created_at, updated_at
FROM
	public.rbac_user_roles
WHERE
	id = $1
`

	// run query
	rur := RbacUserRole{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&rur.ID, &rur.UserID, &rur.RoleID, &rur.CreatedAt, &rur.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &rur, nil
}

// ----- Index Methods for RbacUserRole -----

// RbacUserRoleByUserIDRoleID retrieves a row from 'public.rbac_user_roles' as a RbacUserRole.
//
// Generated from index 'rbac_user_roles_unique'.
func GetRbacUserRoleByUserIDRoleID(db pgxdb.DBQuery, userID int64, roleID int64) (*RbacUserRole, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, user_id, role_id, created_at, updated_at
FROM
	public.rbac_user_roles
WHERE
	user_id = $1 AND role_id = $2
`

	// run query
	rur := RbacUserRole{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, userID, roleID).Scan(&rur.ID, &rur.UserID, &rur.RoleID, &rur.CreatedAt, &rur.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), userID, roleID)

	if err != nil {
		return nil, err
	}

	return &rur, nil
}

// ----- Index Methods for RbacUserRole -----
