// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"errors"
	"fmt"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// RbacPermission represents a row from 'public.rbac_permissions'.
type RbacPermission struct {
	ID        int64     `json:"id"`         // id
	Name      string    `json:"name"`       // name
	Slug      string    `json:"slug"`       // slug
	CreatedAt time.Time `json:"created_at"` // created_at
	UpdatedAt time.Time `json:"updated_at"` // updated_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the RbacPermission exists in the database.
func (rp *RbacPermission) Exists() bool {
	return rp._exists
}

// SetExists determines if the RbacPermission exists in the database.
func (rp *RbacPermission) SetExists(exists bool) {
	rp._exists = exists
}

// Deleted provides information if the RbacPermission has been deleted from the database.
func (rp *RbacPermission) Deleted() bool {
	return rp._deleted
}

// Insert inserts the RbacPermission to the database.
func (rp *RbacPermission) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if rp._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.rbac_permissions (
name, slug, created_at, updated_at
) VALUES (
$1, $2, $3, $4
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, rp.Name, rp.Slug, rp.CreatedAt, rp.UpdatedAt).Scan(&rp.ID)

	db.WriteLog(sqlstr, time.Since(start), rp.Name, rp.Slug, rp.CreatedAt, rp.UpdatedAt)

	if err != nil {
		return err
	}

	// set existence
	rp._exists = true

	return nil
}

// Update updates the RbacPermission in the database.
func (rp *RbacPermission) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !rp._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if rp._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.rbac_permissions SET (
name, slug, created_at, updated_at
) = (
$1, $2, $3, $4
) WHERE id = $5
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rp.Name, rp.Slug, rp.CreatedAt, rp.UpdatedAt, rp.ID)

	db.WriteLog(sqlstr, time.Since(start), rp.Name, rp.Slug, rp.CreatedAt, rp.UpdatedAt, rp.ID)

	return err
}

// Save saves the RbacPermission to the database.
func (rp *RbacPermission) Save(db pgxdb.DBQuery) error {
	if rp.Exists() {
		return rp.Update(db)
	}

	return rp.Insert(db)
}

// Upsert performs an upsert for RbacPermission.
//
// NOTE: PostgreSQL 9.5+ only
func (rp *RbacPermission) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if rp._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.rbac_permissions (
id, name, slug, created_at, updated_at
) VALUES (
$1, $2, $3, $4, $5
) ON CONFLICT (id) DO UPDATE SET (
id, name, slug, created_at, updated_at
) = (
EXCLUDED.id, EXCLUDED.name, EXCLUDED.slug, EXCLUDED.created_at, EXCLUDED.updated_at
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rp.ID, rp.Name, rp.Slug, rp.CreatedAt, rp.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), rp.ID, rp.Name, rp.Slug, rp.CreatedAt, rp.UpdatedAt)

	if err != nil {
		return err
	}

	// set existence
	rp._exists = true

	return nil
}

// Delete deletes the RbacPermission from the database.
func (rp *RbacPermission) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !rp._exists {
		return nil
	}

	// if deleted, bail
	if rp._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.rbac_permissions
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rp.ID)

	db.WriteLog(sqlstr, time.Since(start), rp.ID)

	if err != nil {
		return err
	}

	// set deleted
	rp._deleted = true

	return nil
}

// GetAllRbacPermission returns all rows from 'public.rbac_permissions',
func GetAllRbacPermission(db pgxdb.DBQuery) ([]*RbacPermission, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, slug, created_at, updated_at
FROM public.rbac_permissions
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacPermission
	for q.Next() {
		rp := RbacPermission{}

		// scan
		err = q.Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)
		if err != nil {
			return nil, err
		}
		rp.SetExists(true)

		res = append(res, &rp)
	}

	return res, nil
}

// GetAllRbacPermissionWithPagination returns a paginated set of rows from 'public.rbac_permissions',
func GetAllRbacPermissionWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*RbacPermission, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, slug, created_at, updated_at
FROM public.rbac_permissions
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacPermission
	for q.Next() {
		rp := RbacPermission{}

		// scan
		err = q.Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)
		if err != nil {
			return nil, err
		}
		rp.SetExists(true)

		res = append(res, &rp)
	}

	return res, nil
}

// GetAllRbacPermissionCount returns count of all rows from 'public.rbac_permissions',
func GetAllRbacPermissionCount(db pgxdb.DBQuery) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `SELECT COUNT(*) FROM public.rbac_permissions`

	var count int64
	err := db.QueryRow(ctx, sqlstr).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetRbacPermissionsBySQL returns rows from 'public.rbac_permissions' by your SQL,
func GetRbacPermissionsBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*RbacPermission, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacPermission
	for q.Next() {
		rp := RbacPermission{}

		// scan
		err = q.Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &rp)
	}

	return res, nil
}

// GetRbacPermissionsBySQLWithPagination returns a paginated set of rows from 'public.rbac_permissions' by your SQL,
func GetRbacPermissionsBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*RbacPermission, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacPermission
	for q.Next() {
		rp := RbacPermission{}

		// scan
		err = q.Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &rp)
	}

	return res, nil
}

// GetRbacPermissionsBySQLCount returns count of rows from 'public.rbac_permissions' by your SQL,
func GetRbacPermissionsBySQLCount(db pgxdb.DBQuery, sqlstr string, args ...any) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	var count int64
	err := db.QueryRow(ctx, countSQL, args...).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), args...)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetLastRbacPermission returns last row from 'public.rbac_permissions',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDRbacPermission(db pgxdb.DBQuery) (*RbacPermission, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, slug, created_at, updated_at
FROM public.rbac_permissions
ORDER BY
id DESC
LIMIT 1
`

	var rp RbacPermission
	err := db.QueryRow(ctx, sqlstr).Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	rp._exists = true
	rp._deleted = false

	return &rp, nil
}

// RbacPermissionByID retrieves a row from 'public.rbac_permissions' as a RbacPermission.
//
// Generated from index 'rbac_permissions_pk'.
func GetRbacPermissionByID(db pgxdb.DBQuery, id int64) (*RbacPermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, name, slug, created_at, updated_at
FROM
	public.rbac_permissions
WHERE
	id = $1
`

	// run query
	rp := RbacPermission{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &rp, nil
}

// ----- Index Methods for RbacPermission -----

// RbacPermissionBySlug retrieves a row from 'public.rbac_permissions' as a RbacPermission.
//
// Generated from index 'rbac_permissions_slug_uindex'.
func GetRbacPermissionBySlug(db pgxdb.DBQuery, slug string) (*RbacPermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, name, slug, created_at, updated_at
FROM
	public.rbac_permissions
WHERE
	slug = $1
`

	// run query
	rp := RbacPermission{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, slug).Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), slug)

	if err != nil {
		return nil, err
	}

	return &rp, nil
}

// ----- Index Methods for RbacPermission -----

// GetPermissionsByRoleSlug runs a custom query, returning results as RbacPermission.
func GetPermissionsByRoleSlug(db pgxdb.DBQuery, roleSlug string) ([]*RbacPermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`p.id, p.name, p.slug, p.created_at, p.updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_permissions p ` + "\n" +
		`JOIN public.rbac_role_permissions rp ON p.id = rp.permission_id ` + "\n" +
		`JOIN public.rbac_roles r ON r.id = rp.role_id ` + "\n" +
		`WHERE ` + "\n" +
		`r.slug = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`p.id ASC`

	// run query
	q, err := db.Query(ctx, sqlstr, roleSlug)

	db.WriteLog(sqlstr, time.Since(start), roleSlug)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacPermission{}
	for q.Next() {
		rp := RbacPermission{}

		// scan
		err = q.Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rp._exists = true
		rp._deleted = false

		res = append(res, &rp)
	}

	return res, nil
}

// GetPermissionsByRoleSlugCount runs a custom count query
func GetPermissionsByRoleSlugCount(db pgxdb.DBQuery, roleSlug string) (int64, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`p.id, p.name, p.slug, p.created_at, p.updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_permissions p ` + "\n" +
		`JOIN public.rbac_role_permissions rp ON p.id = rp.permission_id ` + "\n" +
		`JOIN public.rbac_roles r ON r.id = rp.role_id ` + "\n" +
		`WHERE ` + "\n" +
		`r.slug = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`p.id ASC`

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	// run query
	var count int64
	err = db.QueryRow(ctx, countSQL, roleSlug).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), roleSlug)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetPermissionsByRoleSlugWithPagination runs a custom query with pagination
func GetPermissionsByRoleSlugWithPagination(db pgxdb.DBQuery, roleSlug string, limit, offset int) ([]*RbacPermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var baseSQL = `SELECT ` + "\n" +
		`p.id, p.name, p.slug, p.created_at, p.updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_permissions p ` + "\n" +
		`JOIN public.rbac_role_permissions rp ON p.id = rp.permission_id ` + "\n" +
		`JOIN public.rbac_roles r ON r.id = rp.role_id ` + "\n" +
		`WHERE ` + "\n" +
		`r.slug = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`p.id ASC`

	sqlstr := baseSQL + "\nLIMIT $" + fmt.Sprint(1+1) + " OFFSET $" + fmt.Sprint(2+1)

	// run query
	q, err := db.Query(ctx, sqlstr, roleSlug, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), roleSlug, limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacPermission{}
	for q.Next() {
		rp := RbacPermission{}

		// scan
		err = q.Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rp._exists = true
		rp._deleted = false

		res = append(res, &rp)
	}

	return res, nil
}

// GetPermissionsByUserIDAndSlug runs a custom query, returning results as RbacPermission.
func GetPermissionsByUserIDAndSlug(db pgxdb.DBQuery, userID int64, permSlug string) ([]*RbacPermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`p.id, p.name, p.slug, p.created_at, p.updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_permissions p ` + "\n" +
		`JOIN public.rbac_role_permissions rp ON p.id = rp.permission_id ` + "\n" +
		`JOIN public.rbac_user_roles ur ON rp.role_id = ur.role_id ` + "\n" +
		`WHERE ` + "\n" +
		`ur.user_id = $1 ` + "\n" +
		`AND p.slug = $2 ` + "\n" +
		`ORDER BY ` + "\n" +
		`p.id ASC`

	// run query
	q, err := db.Query(ctx, sqlstr, userID, permSlug)

	db.WriteLog(sqlstr, time.Since(start), userID, permSlug)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacPermission{}
	for q.Next() {
		rp := RbacPermission{}

		// scan
		err = q.Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rp._exists = true
		rp._deleted = false

		res = append(res, &rp)
	}

	return res, nil
}

// GetPermissionsByUserIDAndSlugCount runs a custom count query
func GetPermissionsByUserIDAndSlugCount(db pgxdb.DBQuery, userID int64, permSlug string) (int64, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`p.id, p.name, p.slug, p.created_at, p.updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_permissions p ` + "\n" +
		`JOIN public.rbac_role_permissions rp ON p.id = rp.permission_id ` + "\n" +
		`JOIN public.rbac_user_roles ur ON rp.role_id = ur.role_id ` + "\n" +
		`WHERE ` + "\n" +
		`ur.user_id = $1 ` + "\n" +
		`AND p.slug = $2 ` + "\n" +
		`ORDER BY ` + "\n" +
		`p.id ASC`

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	// run query
	var count int64
	err = db.QueryRow(ctx, countSQL, userID, permSlug).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), userID, permSlug)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetPermissionsByUserIDAndSlugWithPagination runs a custom query with pagination
func GetPermissionsByUserIDAndSlugWithPagination(db pgxdb.DBQuery, userID int64, permSlug string, limit, offset int) ([]*RbacPermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var baseSQL = `SELECT ` + "\n" +
		`p.id, p.name, p.slug, p.created_at, p.updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_permissions p ` + "\n" +
		`JOIN public.rbac_role_permissions rp ON p.id = rp.permission_id ` + "\n" +
		`JOIN public.rbac_user_roles ur ON rp.role_id = ur.role_id ` + "\n" +
		`WHERE ` + "\n" +
		`ur.user_id = $1 ` + "\n" +
		`AND p.slug = $2 ` + "\n" +
		`ORDER BY ` + "\n" +
		`p.id ASC`

	sqlstr := baseSQL + "\nLIMIT $" + fmt.Sprint(1+1+1) + " OFFSET $" + fmt.Sprint(2+1+1)

	// run query
	q, err := db.Query(ctx, sqlstr, userID, permSlug, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), userID, permSlug, limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacPermission{}
	for q.Next() {
		rp := RbacPermission{}

		// scan
		err = q.Scan(&rp.ID, &rp.Name, &rp.Slug, &rp.CreatedAt, &rp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rp._exists = true
		rp._deleted = false

		res = append(res, &rp)
	}

	return res, nil
}
