// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"errors"
	"fmt"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// RbacRole represents a row from 'public.rbac_roles'.
type RbacRole struct {
	ID        int64     `json:"id"`         // id
	Name      string    `json:"name"`       // name
	Slug      string    `json:"slug"`       // slug
	CreatedAt time.Time `json:"created_at"` // created_at
	UpdatedAt time.Time `json:"updated_at"` // updated_at

	// @crud
	// xo fields
	_exists, _deleted bool
	// @end-crud

}

// @crud
// Exists determines if the RbacRole exists in the database.
func (rr *RbacRole) Exists() bool {
	return rr._exists
}

// SetExists determines if the RbacRole exists in the database.
func (rr *RbacRole) SetExists(exists bool) {
	rr._exists = exists
}

// Deleted provides information if the RbacRole has been deleted from the database.
func (rr *RbacRole) Deleted() bool {
	return rr._deleted
}

// @end-crud

// @crud
// Insert inserts the RbacRole to the database.
func (rr *RbacRole) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if rr._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.rbac_roles (
name, slug, created_at, updated_at
) VALUES (
$1, $2, $3, $4
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, rr.Name, rr.Slug, rr.CreatedAt, rr.UpdatedAt).Scan(&rr.ID)

	db.WriteLog(sqlstr, time.Since(start), rr.Name, rr.Slug, rr.CreatedAt, rr.UpdatedAt)

	if err != nil {
		return err
	}

	// set existence
	rr._exists = true

	return nil
}

// @end-crud

// @crud

// Update updates the RbacRole in the database.
func (rr *RbacRole) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !rr._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if rr._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.rbac_roles SET (
name, slug, created_at, updated_at
) = (
$1, $2, $3, $4
) WHERE id = $5
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rr.Name, rr.Slug, rr.CreatedAt, rr.UpdatedAt, rr.ID)

	db.WriteLog(sqlstr, time.Since(start), rr.Name, rr.Slug, rr.CreatedAt, rr.UpdatedAt, rr.ID)

	return err
}

// Save saves the RbacRole to the database.
func (rr *RbacRole) Save(db pgxdb.DBQuery) error {
	if rr.Exists() {
		return rr.Update(db)
	}

	return rr.Insert(db)
}

// Upsert performs an upsert for RbacRole.
//
// NOTE: PostgreSQL 9.5+ only
func (rr *RbacRole) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if rr._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.rbac_roles (
id, name, slug, created_at, updated_at
) VALUES (
$1, $2, $3, $4, $5
) ON CONFLICT (id) DO UPDATE SET (
id, name, slug, created_at, updated_at
) = (
EXCLUDED.id, EXCLUDED.name, EXCLUDED.slug, EXCLUDED.created_at, EXCLUDED.updated_at
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rr.ID, rr.Name, rr.Slug, rr.CreatedAt, rr.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), rr.ID, rr.Name, rr.Slug, rr.CreatedAt, rr.UpdatedAt)

	if err != nil {
		return err
	}

	// set existence
	rr._exists = true

	return nil
}

// @end-crud

// @crud
// Delete deletes the RbacRole from the database.
func (rr *RbacRole) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !rr._exists {
		return nil
	}

	// if deleted, bail
	if rr._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.rbac_roles
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rr.ID)

	db.WriteLog(sqlstr, time.Since(start), rr.ID)

	if err != nil {
		return err
	}

	// set deleted
	rr._deleted = true

	return nil
}

// @end-crud

// GetAllRbacRole returns all rows from 'public.rbac_roles',
func GetAllRbacRole(db pgxdb.DBQuery) ([]*RbacRole, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, slug, created_at, updated_at
FROM public.rbac_roles
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacRole
	for q.Next() {
		rr := RbacRole{}

		// scan
		err = q.Scan(&rr.ID, &rr.Name, &rr.Slug, &rr.CreatedAt, &rr.UpdatedAt)
		if err != nil {
			return nil, err
		}
		// @crud
		rr.SetExists(true)
		// @end-crud

		res = append(res, &rr)
	}

	return res, nil
}

// GetAllRbacRoleWithPagination returns a paginated set of rows from 'public.rbac_roles',
func GetAllRbacRoleWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*RbacRole, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, slug, created_at, updated_at
FROM public.rbac_roles
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacRole
	for q.Next() {
		rr := RbacRole{}

		// scan
		err = q.Scan(&rr.ID, &rr.Name, &rr.Slug, &rr.CreatedAt, &rr.UpdatedAt)
		if err != nil {
			return nil, err
		}
		// @crud
		rr.SetExists(true)
		// @end-crud

		res = append(res, &rr)
	}

	return res, nil
}

// GetAllRbacRoleCount returns count of all rows from 'public.rbac_roles',
func GetAllRbacRoleCount(db pgxdb.DBQuery) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `SELECT COUNT(*) FROM public.rbac_roles`

	var count int64
	err := db.QueryRow(ctx, sqlstr).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetRbacRolesBySQL returns rows from 'public.rbac_roles' by your SQL,
func GetRbacRolesBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*RbacRole, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacRole
	for q.Next() {
		rr := RbacRole{}

		// scan
		err = q.Scan(&rr.ID, &rr.Name, &rr.Slug, &rr.CreatedAt, &rr.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &rr)
	}

	return res, nil
}

// GetRbacRolesBySQLWithPagination returns a paginated set of rows from 'public.rbac_roles' by your SQL,
func GetRbacRolesBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*RbacRole, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacRole
	for q.Next() {
		rr := RbacRole{}

		// scan
		err = q.Scan(&rr.ID, &rr.Name, &rr.Slug, &rr.CreatedAt, &rr.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &rr)
	}

	return res, nil
}

// GetRbacRolesBySQLCount returns count of rows from 'public.rbac_roles' by your SQL,
func GetRbacRolesBySQLCount(db pgxdb.DBQuery, sqlstr string, args ...any) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	var count int64
	err := db.QueryRow(ctx, countSQL, args...).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), args...)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetLastRbacRole returns last row from 'public.rbac_roles',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDRbacRole(db pgxdb.DBQuery) (*RbacRole, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, slug, created_at, updated_at
FROM public.rbac_roles
ORDER BY
id DESC
LIMIT 1
`

	var rr RbacRole
	err := db.QueryRow(ctx, sqlstr).Scan(&rr.ID, &rr.Name, &rr.Slug, &rr.CreatedAt, &rr.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	// @crud
	rr._exists = true
	rr._deleted = false
	// @end-crud

	return &rr, nil
}

// RbacRoleByID retrieves a row from 'public.rbac_roles' as a RbacRole.
//
// Generated from index 'rbac_roles_pk'.
func GetRbacRoleByID(db pgxdb.DBQuery, id int64) (*RbacRole, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, name, slug, created_at, updated_at
FROM
	public.rbac_roles
WHERE
	id = $1
`

	// run query
	rr := RbacRole{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&rr.ID, &rr.Name, &rr.Slug, &rr.CreatedAt, &rr.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &rr, nil
}

// ----- Index Methods for RbacRole -----

// RbacRoleBySlug retrieves a row from 'public.rbac_roles' as a RbacRole.
//
// Generated from index 'rbac_roles_slug_uindex'.
func GetRbacRoleBySlug(db pgxdb.DBQuery, slug string) (*RbacRole, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, name, slug, created_at, updated_at
FROM
	public.rbac_roles
WHERE
	slug = $1
`

	// run query
	rr := RbacRole{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, slug).Scan(&rr.ID, &rr.Name, &rr.Slug, &rr.CreatedAt, &rr.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), slug)

	if err != nil {
		return nil, err
	}

	return &rr, nil
}

// ----- Index Methods for RbacRole -----

// GetRolesByUserID runs a custom query, returning results as RbacRole.
func GetRolesByUserID(db pgxdb.DBQuery, userID int64) ([]*RbacRole, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`r.id, r.name, r.slug, r.created_at, r.updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_roles r ` + "\n" +
		`JOIN public.rbac_user_roles ur ON r.id = ur.role_id ` + "\n" +
		`WHERE ` + "\n" +
		`ur.user_id = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`r.id ASC`

	// run query
	q, err := db.Query(ctx, sqlstr, userID)

	db.WriteLog(sqlstr, time.Since(start), userID)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacRole{}
	for q.Next() {
		rr := RbacRole{}

		// scan
		err = q.Scan(&rr.ID, &rr.Name, &rr.Slug, &rr.CreatedAt, &rr.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rr._exists = true
		rr._deleted = false

		res = append(res, &rr)
	}

	return res, nil
}

// GetRolesByUserIDCount runs a custom count query
func GetRolesByUserIDCount(db pgxdb.DBQuery, userID int64) (int64, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`r.id, r.name, r.slug, r.created_at, r.updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_roles r ` + "\n" +
		`JOIN public.rbac_user_roles ur ON r.id = ur.role_id ` + "\n" +
		`WHERE ` + "\n" +
		`ur.user_id = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`r.id ASC`

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	// run query
	var count int64
	err = db.QueryRow(ctx, countSQL, userID).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), userID)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetRolesByUserIDWithPagination runs a custom query with pagination
func GetRolesByUserIDWithPagination(db pgxdb.DBQuery, userID int64, limit, offset int) ([]*RbacRole, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var baseSQL = `SELECT ` + "\n" +
		`r.id, r.name, r.slug, r.created_at, r.updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_roles r ` + "\n" +
		`JOIN public.rbac_user_roles ur ON r.id = ur.role_id ` + "\n" +
		`WHERE ` + "\n" +
		`ur.user_id = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`r.id ASC`

	sqlstr := baseSQL + "\nLIMIT $" + fmt.Sprint(1+1) + " OFFSET $" + fmt.Sprint(2+1)

	// run query
	q, err := db.Query(ctx, sqlstr, userID, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), userID, limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacRole{}
	for q.Next() {
		rr := RbacRole{}

		// scan
		err = q.Scan(&rr.ID, &rr.Name, &rr.Slug, &rr.CreatedAt, &rr.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rr._exists = true
		rr._deleted = false

		res = append(res, &rr)
	}

	return res, nil
}
