// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"errors"
	"fmt"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// RbacRolePermission represents a row from 'public.rbac_role_permissions'.
type RbacRolePermission struct {
	ID           int64     `json:"id"`            // id
	RoleID       int64     `json:"role_id"`       // role_id
	PermissionID int64     `json:"permission_id"` // permission_id
	CreatedAt    time.Time `json:"created_at"`    // created_at
	UpdatedAt    time.Time `json:"updated_at"`    // updated_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the RbacRolePermission exists in the database.
func (rrp *RbacRolePermission) Exists() bool {
	return rrp._exists
}

// SetExists determines if the RbacRolePermission exists in the database.
func (rrp *RbacRolePermission) SetExists(exists bool) {
	rrp._exists = exists
}

// Deleted provides information if the RbacRolePermission has been deleted from the database.
func (rrp *RbacRolePermission) Deleted() bool {
	return rrp._deleted
}

// Insert inserts the RbacRolePermission to the database.
func (rrp *RbacRolePermission) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if rrp._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.rbac_role_permissions (
role_id, permission_id, created_at, updated_at
) VALUES (
$1, $2, $3, $4
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, rrp.RoleID, rrp.PermissionID, rrp.CreatedAt, rrp.UpdatedAt).Scan(&rrp.ID)

	db.WriteLog(sqlstr, time.Since(start), rrp.RoleID, rrp.PermissionID, rrp.CreatedAt, rrp.UpdatedAt)

	if err != nil {
		return err
	}

	// set existence
	rrp._exists = true

	return nil
}

// Update updates the RbacRolePermission in the database.
func (rrp *RbacRolePermission) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !rrp._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if rrp._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.rbac_role_permissions SET (
role_id, permission_id, created_at, updated_at
) = (
$1, $2, $3, $4
) WHERE id = $5
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rrp.RoleID, rrp.PermissionID, rrp.CreatedAt, rrp.UpdatedAt, rrp.ID)

	db.WriteLog(sqlstr, time.Since(start), rrp.RoleID, rrp.PermissionID, rrp.CreatedAt, rrp.UpdatedAt, rrp.ID)

	return err
}

// Save saves the RbacRolePermission to the database.
func (rrp *RbacRolePermission) Save(db pgxdb.DBQuery) error {
	if rrp.Exists() {
		return rrp.Update(db)
	}

	return rrp.Insert(db)
}

// Upsert performs an upsert for RbacRolePermission.
//
// NOTE: PostgreSQL 9.5+ only
func (rrp *RbacRolePermission) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if rrp._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.rbac_role_permissions (
id, role_id, permission_id, created_at, updated_at
) VALUES (
$1, $2, $3, $4, $5
) ON CONFLICT (id) DO UPDATE SET (
id, role_id, permission_id, created_at, updated_at
) = (
EXCLUDED.id, EXCLUDED.role_id, EXCLUDED.permission_id, EXCLUDED.created_at, EXCLUDED.updated_at
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rrp.ID, rrp.RoleID, rrp.PermissionID, rrp.CreatedAt, rrp.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), rrp.ID, rrp.RoleID, rrp.PermissionID, rrp.CreatedAt, rrp.UpdatedAt)

	if err != nil {
		return err
	}

	// set existence
	rrp._exists = true

	return nil
}

// Delete deletes the RbacRolePermission from the database.
func (rrp *RbacRolePermission) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !rrp._exists {
		return nil
	}

	// if deleted, bail
	if rrp._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.rbac_role_permissions
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, rrp.ID)

	db.WriteLog(sqlstr, time.Since(start), rrp.ID)

	if err != nil {
		return err
	}

	// set deleted
	rrp._deleted = true

	return nil
}

// GetAllRbacRolePermission returns all rows from 'public.rbac_role_permissions',
func GetAllRbacRolePermission(db pgxdb.DBQuery) ([]*RbacRolePermission, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, role_id, permission_id, created_at, updated_at
FROM public.rbac_role_permissions
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacRolePermission
	for q.Next() {
		rrp := RbacRolePermission{}

		// scan
		err = q.Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)
		if err != nil {
			return nil, err
		}
		rrp.SetExists(true)

		res = append(res, &rrp)
	}

	return res, nil
}

// GetAllRbacRolePermissionWithPagination returns a paginated set of rows from 'public.rbac_role_permissions',
func GetAllRbacRolePermissionWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*RbacRolePermission, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, role_id, permission_id, created_at, updated_at
FROM public.rbac_role_permissions
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacRolePermission
	for q.Next() {
		rrp := RbacRolePermission{}

		// scan
		err = q.Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)
		if err != nil {
			return nil, err
		}
		rrp.SetExists(true)

		res = append(res, &rrp)
	}

	return res, nil
}

// GetAllRbacRolePermissionCount returns count of all rows from 'public.rbac_role_permissions',
func GetAllRbacRolePermissionCount(db pgxdb.DBQuery) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `SELECT COUNT(*) FROM public.rbac_role_permissions`

	var count int64
	err := db.QueryRow(ctx, sqlstr).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetRbacRolePermissionsBySQL returns rows from 'public.rbac_role_permissions' by your SQL,
func GetRbacRolePermissionsBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*RbacRolePermission, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacRolePermission
	for q.Next() {
		rrp := RbacRolePermission{}

		// scan
		err = q.Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &rrp)
	}

	return res, nil
}

// GetRbacRolePermissionsBySQLWithPagination returns a paginated set of rows from 'public.rbac_role_permissions' by your SQL,
func GetRbacRolePermissionsBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*RbacRolePermission, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*RbacRolePermission
	for q.Next() {
		rrp := RbacRolePermission{}

		// scan
		err = q.Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &rrp)
	}

	return res, nil
}

// GetRbacRolePermissionsBySQLCount returns count of rows from 'public.rbac_role_permissions' by your SQL,
func GetRbacRolePermissionsBySQLCount(db pgxdb.DBQuery, sqlstr string, args ...any) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	var count int64
	err := db.QueryRow(ctx, countSQL, args...).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), args...)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetLastRbacRolePermission returns last row from 'public.rbac_role_permissions',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDRbacRolePermission(db pgxdb.DBQuery) (*RbacRolePermission, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, role_id, permission_id, created_at, updated_at
FROM public.rbac_role_permissions
ORDER BY
id DESC
LIMIT 1
`

	var rrp RbacRolePermission
	err := db.QueryRow(ctx, sqlstr).Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	rrp._exists = true
	rrp._deleted = false

	return &rrp, nil
}

// RbacPermission returns the RbacPermission associated with the RbacRolePermission's PermissionID (permission_id).
//
// Generated from foreign key 'rbac_role_permissions_permissions_fk'.
func (rrp *RbacRolePermission) GetRbacPermission(db pgxdb.DBQuery) (*RbacPermission, error) {
	return GetRbacPermissionByID(db, rrp.PermissionID)
}

// RbacRole returns the RbacRole associated with the RbacRolePermission's RoleID (role_id).
//
// Generated from foreign key 'rbac_role_permissions_roles_fk'.
func (rrp *RbacRolePermission) GetRbacRole(db pgxdb.DBQuery) (*RbacRole, error) {
	return GetRbacRoleByID(db, rrp.RoleID)
}

// RbacRolePermissionByID retrieves a row from 'public.rbac_role_permissions' as a RbacRolePermission.
//
// Generated from index 'rbac_role_permissions_pk'.
func GetRbacRolePermissionByID(db pgxdb.DBQuery, id int64) (*RbacRolePermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, role_id, permission_id, created_at, updated_at
FROM
	public.rbac_role_permissions
WHERE
	id = $1
`

	// run query
	rrp := RbacRolePermission{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &rrp, nil
}

// ----- Index Methods for RbacRolePermission -----

// RbacRolePermissionByRoleIDPermissionID retrieves a row from 'public.rbac_role_permissions' as a RbacRolePermission.
//
// Generated from index 'rbac_role_permissions_unique'.
func GetRbacRolePermissionByRoleIDPermissionID(db pgxdb.DBQuery, roleID int64, permissionID int64) (*RbacRolePermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, role_id, permission_id, created_at, updated_at
FROM
	public.rbac_role_permissions
WHERE
	role_id = $1 AND permission_id = $2
`

	// run query
	rrp := RbacRolePermission{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, roleID, permissionID).Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)

	db.WriteLog(sqlstr, time.Since(start), roleID, permissionID)

	if err != nil {
		return nil, err
	}

	return &rrp, nil
}

// ----- Index Methods for RbacRolePermission -----

// GetRbacRolePermissionByPermissionID runs a custom query, returning results as RbacRolePermission.
func GetRbacRolePermissionByPermissionID(db pgxdb.DBQuery, permissionID int64) ([]*RbacRolePermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`id, role_id, permission_id, created_at, updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_role_permissions ` + "\n" +
		`WHERE ` + "\n" +
		`permission_id = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`id ASC`

	// run query
	q, err := db.Query(ctx, sqlstr, permissionID)

	db.WriteLog(sqlstr, time.Since(start), permissionID)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacRolePermission{}
	for q.Next() {
		rrp := RbacRolePermission{}

		// scan
		err = q.Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rrp._exists = true
		rrp._deleted = false

		res = append(res, &rrp)
	}

	return res, nil
}

// GetRbacRolePermissionByPermissionIDCount runs a custom count query
func GetRbacRolePermissionByPermissionIDCount(db pgxdb.DBQuery, permissionID int64) (int64, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`id, role_id, permission_id, created_at, updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_role_permissions ` + "\n" +
		`WHERE ` + "\n" +
		`permission_id = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`id ASC`

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	// run query
	var count int64
	err = db.QueryRow(ctx, countSQL, permissionID).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), permissionID)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetRbacRolePermissionByPermissionIDWithPagination runs a custom query with pagination
func GetRbacRolePermissionByPermissionIDWithPagination(db pgxdb.DBQuery, permissionID int64, limit, offset int) ([]*RbacRolePermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var baseSQL = `SELECT ` + "\n" +
		`id, role_id, permission_id, created_at, updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_role_permissions ` + "\n" +
		`WHERE ` + "\n" +
		`permission_id = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`id ASC`

	sqlstr := baseSQL + "\nLIMIT $" + fmt.Sprint(1+1) + " OFFSET $" + fmt.Sprint(2+1)

	// run query
	q, err := db.Query(ctx, sqlstr, permissionID, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), permissionID, limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacRolePermission{}
	for q.Next() {
		rrp := RbacRolePermission{}

		// scan
		err = q.Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rrp._exists = true
		rrp._deleted = false

		res = append(res, &rrp)
	}

	return res, nil
}

// GetRbacRolePermissionByRoleID runs a custom query, returning results as RbacRolePermission.
func GetRbacRolePermissionByRoleID(db pgxdb.DBQuery, roleID int64) ([]*RbacRolePermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`id, role_id, permission_id, created_at, updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_role_permissions ` + "\n" +
		`WHERE ` + "\n" +
		`role_id = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`id ASC`

	// run query
	q, err := db.Query(ctx, sqlstr, roleID)

	db.WriteLog(sqlstr, time.Since(start), roleID)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacRolePermission{}
	for q.Next() {
		rrp := RbacRolePermission{}

		// scan
		err = q.Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rrp._exists = true
		rrp._deleted = false

		res = append(res, &rrp)
	}

	return res, nil
}

// GetRbacRolePermissionByRoleIDCount runs a custom count query
func GetRbacRolePermissionByRoleIDCount(db pgxdb.DBQuery, roleID int64) (int64, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`id, role_id, permission_id, created_at, updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_role_permissions ` + "\n" +
		`WHERE ` + "\n" +
		`role_id = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`id ASC`

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	// run query
	var count int64
	err = db.QueryRow(ctx, countSQL, roleID).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), roleID)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetRbacRolePermissionByRoleIDWithPagination runs a custom query with pagination
func GetRbacRolePermissionByRoleIDWithPagination(db pgxdb.DBQuery, roleID int64, limit, offset int) ([]*RbacRolePermission, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var baseSQL = `SELECT ` + "\n" +
		`id, role_id, permission_id, created_at, updated_at ` + "\n" +
		`FROM ` + "\n" +
		`public.rbac_role_permissions ` + "\n" +
		`WHERE ` + "\n" +
		`role_id = $1 ` + "\n" +
		`ORDER BY ` + "\n" +
		`id ASC`

	sqlstr := baseSQL + "\nLIMIT $" + fmt.Sprint(1+1) + " OFFSET $" + fmt.Sprint(2+1)

	// run query
	q, err := db.Query(ctx, sqlstr, roleID, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), roleID, limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*RbacRolePermission{}
	for q.Next() {
		rrp := RbacRolePermission{}

		// scan
		err = q.Scan(&rrp.ID, &rrp.RoleID, &rrp.PermissionID, &rrp.CreatedAt, &rrp.UpdatedAt)
		if err != nil {
			return nil, err
		}

		rrp._exists = true
		rrp._deleted = false

		res = append(res, &rrp)
	}

	return res, nil
}
