// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"errors"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// SchemaMigration represents a row from 'public.schema_migrations'.
type SchemaMigration struct {
	Version int64 `json:"version"` // version
	Dirty   bool  `json:"dirty"`   // dirty

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the SchemaMigration exists in the database.
func (sm *SchemaMigration) Exists() bool {
	return sm._exists
}

// SetExists determines if the SchemaMigration exists in the database.
func (sm *SchemaMigration) SetExists(exists bool) {
	sm._exists = exists
}

// Deleted provides information if the SchemaMigration has been deleted from the database.
func (sm *SchemaMigration) Deleted() bool {
	return sm._deleted
}

// Insert inserts the SchemaMigration to the database.
func (sm *SchemaMigration) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if sm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	// language=SQL
	const sqlstr = `
INSERT INTO public.schema_migrations (
version, dirty
) VALUES (
$1, $2
) RETURNING version
`

	// run query
	err = db.QueryRow(ctx, sqlstr, sm.Version, sm.Dirty).Scan(&sm.Version)

	db.WriteLog(sqlstr, time.Since(start), sm.Version, sm.Dirty)

	if err != nil {
		return err
	}

	// set existence
	sm._exists = true

	return nil
}

// Update updates the SchemaMigration in the database.
func (sm *SchemaMigration) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !sm._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if sm._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.schema_migrations SET (
dirty
) = (
$1
) WHERE version = $2
`

	// run query
	_, err = db.Exec(ctx, sqlstr, sm.Dirty, sm.Version)

	db.WriteLog(sqlstr, time.Since(start), sm.Dirty, sm.Version)

	return err
}

// Save saves the SchemaMigration to the database.
func (sm *SchemaMigration) Save(db pgxdb.DBQuery) error {
	if sm.Exists() {
		return sm.Update(db)
	}

	return sm.Insert(db)
}

// Upsert performs an upsert for SchemaMigration.
//
// NOTE: PostgreSQL 9.5+ only
func (sm *SchemaMigration) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if sm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.schema_migrations (
version, dirty
) VALUES (
$1, $2
) ON CONFLICT (version) DO UPDATE SET (
version, dirty
) = (
EXCLUDED.version, EXCLUDED.dirty
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, sm.Version, sm.Dirty)

	db.WriteLog(sqlstr, time.Since(start), sm.Version, sm.Dirty)

	if err != nil {
		return err
	}

	// set existence
	sm._exists = true

	return nil
}

// Delete deletes the SchemaMigration from the database.
func (sm *SchemaMigration) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !sm._exists {
		return nil
	}

	// if deleted, bail
	if sm._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.schema_migrations
WHERE version = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, sm.Version)

	db.WriteLog(sqlstr, time.Since(start), sm.Version)

	if err != nil {
		return err
	}

	// set deleted
	sm._deleted = true

	return nil
}

// GetAllSchemaMigration returns all rows from 'public.schema_migrations',
func GetAllSchemaMigration(db pgxdb.DBQuery) ([]*SchemaMigration, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
version, dirty
FROM public.schema_migrations
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SchemaMigration
	for q.Next() {
		sm := SchemaMigration{}

		// scan
		err = q.Scan(&sm.Version, &sm.Dirty)
		if err != nil {
			return nil, err
		}
		sm.SetExists(true)

		res = append(res, &sm)
	}

	return res, nil
}

// GetSchemaMigrationsBySQL returns rows from 'public.schema_migrations' by your SQL,
func GetSchemaMigrationsBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*SchemaMigration, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SchemaMigration
	for q.Next() {
		sm := SchemaMigration{}

		// scan
		err = q.Scan(&sm.Version, &sm.Dirty)
		if err != nil {
			return nil, err
		}

		res = append(res, &sm)
	}

	return res, nil
}

// GetLastSchemaMigration returns last row from 'public.schema_migrations',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDSchemaMigration(db pgxdb.DBQuery) (*SchemaMigration, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
version, dirty
FROM public.schema_migrations
ORDER BY
id DESC
LIMIT 1
`

	var sm SchemaMigration
	err := db.QueryRow(ctx, sqlstr).Scan(&sm.Version, &sm.Dirty)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	sm._exists = true
	sm._deleted = false

	return &sm, nil
}

// SchemaMigrationByVersion retrieves a row from 'public.schema_migrations' as a SchemaMigration.
//
// Generated from index 'schema_migrations_pkey'.
func GetSchemaMigrationByVersion(db pgxdb.DBQuery, version int64) (*SchemaMigration, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	version, dirty
FROM
	public.schema_migrations
WHERE
	version = $1
`

	// run query
	sm := SchemaMigration{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, version).Scan(&sm.Version, &sm.Dirty)

	db.WriteLog(sqlstr, time.Since(start), version)

	if err != nil {
		return nil, err
	}

	return &sm, nil
}

// ----- Index Methods for SchemaMigration -----
