// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// SettingsGroup represents a row from 'public.settings_groups'.
type SettingsGroup struct {
	ID          int64          `json:"id"`          // id
	Name        string         `json:"name"`        // name
	Description sql.NullString `json:"description"` // description
	OrderPos    int64          `json:"order_pos"`   // order_pos

	// @crud
	// xo fields
	_exists, _deleted bool
	// @end-crud

}

// @crud
// Exists determines if the SettingsGroup exists in the database.
func (sg *SettingsGroup) Exists() bool {
	return sg._exists
}

// SetExists determines if the SettingsGroup exists in the database.
func (sg *SettingsGroup) SetExists(exists bool) {
	sg._exists = exists
}

// Deleted provides information if the SettingsGroup has been deleted from the database.
func (sg *SettingsGroup) Deleted() bool {
	return sg._deleted
}

// @end-crud

// @crud
// Insert inserts the SettingsGroup to the database.
func (sg *SettingsGroup) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if sg._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.settings_groups (
name, description, order_pos
) VALUES (
$1, $2, $3
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, sg.Name, sg.Description, sg.OrderPos).Scan(&sg.ID)

	db.WriteLog(sqlstr, time.Since(start), sg.Name, sg.Description, sg.OrderPos)

	if err != nil {
		return err
	}

	// set existence
	sg._exists = true

	return nil
}

// @end-crud

// @crud

// Update updates the SettingsGroup in the database.
func (sg *SettingsGroup) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !sg._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if sg._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.settings_groups SET (
name, description, order_pos
) = (
$1, $2, $3
) WHERE id = $4
`

	// run query
	_, err = db.Exec(ctx, sqlstr, sg.Name, sg.Description, sg.OrderPos, sg.ID)

	db.WriteLog(sqlstr, time.Since(start), sg.Name, sg.Description, sg.OrderPos, sg.ID)

	return err
}

// Save saves the SettingsGroup to the database.
func (sg *SettingsGroup) Save(db pgxdb.DBQuery) error {
	if sg.Exists() {
		return sg.Update(db)
	}

	return sg.Insert(db)
}

// Upsert performs an upsert for SettingsGroup.
//
// NOTE: PostgreSQL 9.5+ only
func (sg *SettingsGroup) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if sg._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.settings_groups (
id, name, description, order_pos
) VALUES (
$1, $2, $3, $4
) ON CONFLICT (id) DO UPDATE SET (
id, name, description, order_pos
) = (
EXCLUDED.id, EXCLUDED.name, EXCLUDED.description, EXCLUDED.order_pos
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, sg.ID, sg.Name, sg.Description, sg.OrderPos)

	db.WriteLog(sqlstr, time.Since(start), sg.ID, sg.Name, sg.Description, sg.OrderPos)

	if err != nil {
		return err
	}

	// set existence
	sg._exists = true

	return nil
}

// @end-crud

// @crud
// Delete deletes the SettingsGroup from the database.
func (sg *SettingsGroup) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !sg._exists {
		return nil
	}

	// if deleted, bail
	if sg._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.settings_groups
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, sg.ID)

	db.WriteLog(sqlstr, time.Since(start), sg.ID)

	if err != nil {
		return err
	}

	// set deleted
	sg._deleted = true

	return nil
}

// @end-crud

// GetAllSettingsGroup returns all rows from 'public.settings_groups',
func GetAllSettingsGroup(db pgxdb.DBQuery) ([]*SettingsGroup, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, description, order_pos
FROM public.settings_groups
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SettingsGroup
	for q.Next() {
		sg := SettingsGroup{}

		// scan
		err = q.Scan(&sg.ID, &sg.Name, &sg.Description, &sg.OrderPos)
		if err != nil {
			return nil, err
		}
		// @crud
		sg.SetExists(true)
		// @end-crud

		res = append(res, &sg)
	}

	return res, nil
}

// GetAllSettingsGroupWithPagination returns a paginated set of rows from 'public.settings_groups',
func GetAllSettingsGroupWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*SettingsGroup, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, description, order_pos
FROM public.settings_groups
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SettingsGroup
	for q.Next() {
		sg := SettingsGroup{}

		// scan
		err = q.Scan(&sg.ID, &sg.Name, &sg.Description, &sg.OrderPos)
		if err != nil {
			return nil, err
		}
		// @crud
		sg.SetExists(true)
		// @end-crud

		res = append(res, &sg)
	}

	return res, nil
}

// GetAllSettingsGroupCount returns count of all rows from 'public.settings_groups',
func GetAllSettingsGroupCount(db pgxdb.DBQuery) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `SELECT COUNT(*) FROM public.settings_groups`

	var count int64
	err := db.QueryRow(ctx, sqlstr).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetSettingsGroupsBySQL returns rows from 'public.settings_groups' by your SQL,
func GetSettingsGroupsBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*SettingsGroup, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SettingsGroup
	for q.Next() {
		sg := SettingsGroup{}

		// scan
		err = q.Scan(&sg.ID, &sg.Name, &sg.Description, &sg.OrderPos)
		if err != nil {
			return nil, err
		}

		res = append(res, &sg)
	}

	return res, nil
}

// GetSettingsGroupsBySQLWithPagination returns a paginated set of rows from 'public.settings_groups' by your SQL,
func GetSettingsGroupsBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*SettingsGroup, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SettingsGroup
	for q.Next() {
		sg := SettingsGroup{}

		// scan
		err = q.Scan(&sg.ID, &sg.Name, &sg.Description, &sg.OrderPos)
		if err != nil {
			return nil, err
		}

		res = append(res, &sg)
	}

	return res, nil
}

// GetSettingsGroupsBySQLCount returns count of rows from 'public.settings_groups' by your SQL,
func GetSettingsGroupsBySQLCount(db pgxdb.DBQuery, sqlstr string, args ...any) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	var count int64
	err := db.QueryRow(ctx, countSQL, args...).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), args...)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetLastSettingsGroup returns last row from 'public.settings_groups',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDSettingsGroup(db pgxdb.DBQuery) (*SettingsGroup, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, description, order_pos
FROM public.settings_groups
ORDER BY
id DESC
LIMIT 1
`

	var sg SettingsGroup
	err := db.QueryRow(ctx, sqlstr).Scan(&sg.ID, &sg.Name, &sg.Description, &sg.OrderPos)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	// @crud
	sg._exists = true
	sg._deleted = false
	// @end-crud

	return &sg, nil
}

// SettingsGroupByID retrieves a row from 'public.settings_groups' as a SettingsGroup.
//
// Generated from index 'settings_groups_pk'.
func GetSettingsGroupByID(db pgxdb.DBQuery, id int64) (*SettingsGroup, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, name, description, order_pos
FROM
	public.settings_groups
WHERE
	id = $1
`

	// run query
	sg := SettingsGroup{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&sg.ID, &sg.Name, &sg.Description, &sg.OrderPos)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &sg, nil
}

// ----- Index Methods for SettingsGroup -----
