// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// SettingsType represents a row from 'public.settings_types'.
type SettingsType struct {
	ID          int64          `json:"id"`          // id
	Name        string         `json:"name"`        // name
	Description sql.NullString `json:"description"` // description

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the SettingsType exists in the database.
func (st *SettingsType) Exists() bool {
	return st._exists
}

// SetExists determines if the SettingsType exists in the database.
func (st *SettingsType) SetExists(exists bool) {
	st._exists = exists
}

// Deleted provides information if the SettingsType has been deleted from the database.
func (st *SettingsType) Deleted() bool {
	return st._deleted
}

// Insert inserts the SettingsType to the database.
func (st *SettingsType) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if st._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.settings_types (
name, description
) VALUES (
$1, $2
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, st.Name, st.Description).Scan(&st.ID)

	db.WriteLog(sqlstr, time.Since(start), st.Name, st.Description)

	if err != nil {
		return err
	}

	// set existence
	st._exists = true

	return nil
}

// Update updates the SettingsType in the database.
func (st *SettingsType) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !st._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if st._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.settings_types SET (
name, description
) = (
$1, $2
) WHERE id = $3
`

	// run query
	_, err = db.Exec(ctx, sqlstr, st.Name, st.Description, st.ID)

	db.WriteLog(sqlstr, time.Since(start), st.Name, st.Description, st.ID)

	return err
}

// Save saves the SettingsType to the database.
func (st *SettingsType) Save(db pgxdb.DBQuery) error {
	if st.Exists() {
		return st.Update(db)
	}

	return st.Insert(db)
}

// Upsert performs an upsert for SettingsType.
//
// NOTE: PostgreSQL 9.5+ only
func (st *SettingsType) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if st._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.settings_types (
id, name, description
) VALUES (
$1, $2, $3
) ON CONFLICT (id) DO UPDATE SET (
id, name, description
) = (
EXCLUDED.id, EXCLUDED.name, EXCLUDED.description
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, st.ID, st.Name, st.Description)

	db.WriteLog(sqlstr, time.Since(start), st.ID, st.Name, st.Description)

	if err != nil {
		return err
	}

	// set existence
	st._exists = true

	return nil
}

// Delete deletes the SettingsType from the database.
func (st *SettingsType) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !st._exists {
		return nil
	}

	// if deleted, bail
	if st._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.settings_types
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, st.ID)

	db.WriteLog(sqlstr, time.Since(start), st.ID)

	if err != nil {
		return err
	}

	// set deleted
	st._deleted = true

	return nil
}

// GetAllSettingsType returns all rows from 'public.settings_types',
func GetAllSettingsType(db pgxdb.DBQuery) ([]*SettingsType, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, description
FROM public.settings_types
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SettingsType
	for q.Next() {
		st := SettingsType{}

		// scan
		err = q.Scan(&st.ID, &st.Name, &st.Description)
		if err != nil {
			return nil, err
		}
		st.SetExists(true)

		res = append(res, &st)
	}

	return res, nil
}

// GetAllSettingsTypeWithPagination returns a paginated set of rows from 'public.settings_types',
func GetAllSettingsTypeWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*SettingsType, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, description
FROM public.settings_types
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SettingsType
	for q.Next() {
		st := SettingsType{}

		// scan
		err = q.Scan(&st.ID, &st.Name, &st.Description)
		if err != nil {
			return nil, err
		}
		st.SetExists(true)

		res = append(res, &st)
	}

	return res, nil
}

// GetAllSettingsTypeCount returns count of all rows from 'public.settings_types',
func GetAllSettingsTypeCount(db pgxdb.DBQuery) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `SELECT COUNT(*) FROM public.settings_types`

	var count int64
	err := db.QueryRow(ctx, sqlstr).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetSettingsTypesBySQL returns rows from 'public.settings_types' by your SQL,
func GetSettingsTypesBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*SettingsType, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SettingsType
	for q.Next() {
		st := SettingsType{}

		// scan
		err = q.Scan(&st.ID, &st.Name, &st.Description)
		if err != nil {
			return nil, err
		}

		res = append(res, &st)
	}

	return res, nil
}

// GetSettingsTypesBySQLWithPagination returns a paginated set of rows from 'public.settings_types' by your SQL,
func GetSettingsTypesBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*SettingsType, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*SettingsType
	for q.Next() {
		st := SettingsType{}

		// scan
		err = q.Scan(&st.ID, &st.Name, &st.Description)
		if err != nil {
			return nil, err
		}

		res = append(res, &st)
	}

	return res, nil
}

// GetSettingsTypesBySQLCount returns count of rows from 'public.settings_types' by your SQL,
func GetSettingsTypesBySQLCount(db pgxdb.DBQuery, sqlstr string, args ...any) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	var count int64
	err := db.QueryRow(ctx, countSQL, args...).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), args...)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetLastSettingsType returns last row from 'public.settings_types',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDSettingsType(db pgxdb.DBQuery) (*SettingsType, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, description
FROM public.settings_types
ORDER BY
id DESC
LIMIT 1
`

	var st SettingsType
	err := db.QueryRow(ctx, sqlstr).Scan(&st.ID, &st.Name, &st.Description)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	st._exists = true
	st._deleted = false

	return &st, nil
}

// SettingsTypeByName retrieves a row from 'public.settings_types' as a SettingsType.
//
// Generated from index 'settings_types_name_uindex'.
func GetSettingsTypeByName(db pgxdb.DBQuery, name string) (*SettingsType, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, name, description
FROM
	public.settings_types
WHERE
	name = $1
`

	// run query
	st := SettingsType{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, name).Scan(&st.ID, &st.Name, &st.Description)

	db.WriteLog(sqlstr, time.Since(start), name)

	if err != nil {
		return nil, err
	}

	return &st, nil
}

// ----- Index Methods for SettingsType -----

// SettingsTypeByID retrieves a row from 'public.settings_types' as a SettingsType.
//
// Generated from index 'settings_types_pk'.
func GetSettingsTypeByID(db pgxdb.DBQuery, id int64) (*SettingsType, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, name, description
FROM
	public.settings_types
WHERE
	id = $1
`

	// run query
	st := SettingsType{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&st.ID, &st.Name, &st.Description)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &st, nil
}

// ----- Index Methods for SettingsType -----
