// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// Setting represents a row from 'public.settings'.
type Setting struct {
	ID              int64          `json:"id"`               // id
	TypeID          int64          `json:"type_id"`          // type_id
	GroupID         int64          `json:"group_id"`         // group_id
	Name            string         `json:"name"`             // name
	Description     sql.NullString `json:"description"`      // description
	AvailableValues JSON           `json:"available_values"` // available_values
	DefaultValue    JSON           `json:"default_value"`    // default_value

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Setting exists in the database.
func (s *Setting) Exists() bool {
	return s._exists
}

// SetExists determines if the Setting exists in the database.
func (s *Setting) SetExists(exists bool) {
	s._exists = exists
}

// Deleted provides information if the Setting has been deleted from the database.
func (s *Setting) Deleted() bool {
	return s._deleted
}

// Insert inserts the Setting to the database.
func (s *Setting) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if s._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.settings (
type_id, group_id, name, description, available_values, default_value
) VALUES (
$1, $2, $3, $4, $5, $6
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, s.TypeID, s.GroupID, s.Name, s.Description, s.AvailableValues, s.DefaultValue).Scan(&s.ID)

	db.WriteLog(sqlstr, time.Since(start), s.TypeID, s.GroupID, s.Name, s.Description, s.AvailableValues, s.DefaultValue)

	if err != nil {
		return err
	}

	// set existence
	s._exists = true

	return nil
}

// Update updates the Setting in the database.
func (s *Setting) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !s._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if s._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.settings SET (
type_id, group_id, name, description, available_values, default_value
) = (
$1, $2, $3, $4, $5, $6
) WHERE id = $7
`

	// run query
	_, err = db.Exec(ctx, sqlstr, s.TypeID, s.GroupID, s.Name, s.Description, s.AvailableValues, s.DefaultValue, s.ID)

	db.WriteLog(sqlstr, time.Since(start), s.TypeID, s.GroupID, s.Name, s.Description, s.AvailableValues, s.DefaultValue, s.ID)

	return err
}

// Save saves the Setting to the database.
func (s *Setting) Save(db pgxdb.DBQuery) error {
	if s.Exists() {
		return s.Update(db)
	}

	return s.Insert(db)
}

// Upsert performs an upsert for Setting.
//
// NOTE: PostgreSQL 9.5+ only
func (s *Setting) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if s._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.settings (
id, type_id, group_id, name, description, available_values, default_value
) VALUES (
$1, $2, $3, $4, $5, $6, $7
) ON CONFLICT (id) DO UPDATE SET (
id, type_id, group_id, name, description, available_values, default_value
) = (
EXCLUDED.id, EXCLUDED.type_id, EXCLUDED.group_id, EXCLUDED.name, EXCLUDED.description, EXCLUDED.available_values, EXCLUDED.default_value
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, s.ID, s.TypeID, s.GroupID, s.Name, s.Description, s.AvailableValues, s.DefaultValue)

	db.WriteLog(sqlstr, time.Since(start), s.ID, s.TypeID, s.GroupID, s.Name, s.Description, s.AvailableValues, s.DefaultValue)

	if err != nil {
		return err
	}

	// set existence
	s._exists = true

	return nil
}

// Delete deletes the Setting from the database.
func (s *Setting) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !s._exists {
		return nil
	}

	// if deleted, bail
	if s._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.settings
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, s.ID)

	db.WriteLog(sqlstr, time.Since(start), s.ID)

	if err != nil {
		return err
	}

	// set deleted
	s._deleted = true

	return nil
}

// GetAllSetting returns all rows from 'public.settings',
func GetAllSetting(db pgxdb.DBQuery) ([]*Setting, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, type_id, group_id, name, description, available_values, default_value
FROM public.settings
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*Setting
	for q.Next() {
		s := Setting{}

		// scan
		err = q.Scan(&s.ID, &s.TypeID, &s.GroupID, &s.Name, &s.Description, &s.AvailableValues, &s.DefaultValue)
		if err != nil {
			return nil, err
		}
		s.SetExists(true)

		res = append(res, &s)
	}

	return res, nil
}

// GetAllSettingWithPagination returns a paginated set of rows from 'public.settings',
func GetAllSettingWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*Setting, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, type_id, group_id, name, description, available_values, default_value
FROM public.settings
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*Setting
	for q.Next() {
		s := Setting{}

		// scan
		err = q.Scan(&s.ID, &s.TypeID, &s.GroupID, &s.Name, &s.Description, &s.AvailableValues, &s.DefaultValue)
		if err != nil {
			return nil, err
		}
		s.SetExists(true)

		res = append(res, &s)
	}

	return res, nil
}

// GetAllSettingCount returns count of all rows from 'public.settings',
func GetAllSettingCount(db pgxdb.DBQuery) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `SELECT COUNT(*) FROM public.settings`

	var count int64
	err := db.QueryRow(ctx, sqlstr).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetSettingsBySQL returns rows from 'public.settings' by your SQL,
func GetSettingsBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*Setting, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*Setting
	for q.Next() {
		s := Setting{}

		// scan
		err = q.Scan(&s.ID, &s.TypeID, &s.GroupID, &s.Name, &s.Description, &s.AvailableValues, &s.DefaultValue)
		if err != nil {
			return nil, err
		}

		res = append(res, &s)
	}

	return res, nil
}

// GetSettingsBySQLWithPagination returns a paginated set of rows from 'public.settings' by your SQL,
func GetSettingsBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*Setting, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*Setting
	for q.Next() {
		s := Setting{}

		// scan
		err = q.Scan(&s.ID, &s.TypeID, &s.GroupID, &s.Name, &s.Description, &s.AvailableValues, &s.DefaultValue)
		if err != nil {
			return nil, err
		}

		res = append(res, &s)
	}

	return res, nil
}

// GetSettingsBySQLCount returns count of rows from 'public.settings' by your SQL,
func GetSettingsBySQLCount(db pgxdb.DBQuery, sqlstr string, args ...any) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	var count int64
	err := db.QueryRow(ctx, countSQL, args...).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), args...)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetLastSetting returns last row from 'public.settings',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDSetting(db pgxdb.DBQuery) (*Setting, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, type_id, group_id, name, description, available_values, default_value
FROM public.settings
ORDER BY
id DESC
LIMIT 1
`

	var s Setting
	err := db.QueryRow(ctx, sqlstr).Scan(&s.ID, &s.TypeID, &s.GroupID, &s.Name, &s.Description, &s.AvailableValues, &s.DefaultValue)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	s._exists = true
	s._deleted = false

	return &s, nil
}

// SettingsGroup returns the SettingsGroup associated with the Setting's GroupID (group_id).
//
// Generated from foreign key 'settings_settings_groups_id_fk'.
func (s *Setting) GetSettingsGroup(db pgxdb.DBQuery) (*SettingsGroup, error) {
	return GetSettingsGroupByID(db, s.GroupID)
}

// SettingsType returns the SettingsType associated with the Setting's TypeID (type_id).
//
// Generated from foreign key 'settings_settings_types_id_fk'.
func (s *Setting) GetSettingsType(db pgxdb.DBQuery) (*SettingsType, error) {
	return GetSettingsTypeByID(db, s.TypeID)
}

// SettingByID retrieves a row from 'public.settings' as a Setting.
//
// Generated from index 'settings_pk'.
func GetSettingByID(db pgxdb.DBQuery, id int64) (*Setting, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, type_id, group_id, name, description, available_values, default_value
FROM
	public.settings
WHERE
	id = $1
`

	// run query
	s := Setting{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&s.ID, &s.TypeID, &s.GroupID, &s.Name, &s.Description, &s.AvailableValues, &s.DefaultValue)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &s, nil
}

// ----- Index Methods for Setting -----
