// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xouid. DO NOT EDIT.

import (
	"context"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// Custom Query
func DeleteExpiredTokens(db pgxdb.DBQuery, ttlDays int) (err error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	sqlstr := `
UPDATE public.users_tokens
SET deleted_at = (NOW() AT TIME ZONE 'UTC'), updated_at = (NOW() AT TIME ZONE 'UTC')
WHERE deleted_at IS NULL
  AND (
          CASE
              WHEN last_used_at IS NOT NULL THEN last_used_at
              ELSE created_at
              END
          ) < (NOW() AT TIME ZONE 'UTC') - make_interval(days => $1)

	`

	_, err = db.Exec(ctx, sqlstr, ttlDays)

	db.WriteLog(sqlstr, time.Since(start), ttlDays)

	return err
}
