// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/lib/pq"
	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// User represents a row from 'public.users'.
type User struct {
	ID              int64       `json:"id"`                // id
	Name            string      `json:"name"`              // name
	Email           string      `json:"email"`             // email
	Password        string      `json:"password"`          // password
	EmailVerifiedAt pq.NullTime `json:"email_verified_at"` // email_verified_at
	CreatedAt       time.Time   `json:"created_at"`        // created_at
	UpdatedAt       time.Time   `json:"updated_at"`        // updated_at
	DeletedAt       pq.NullTime `json:"deleted_at"`        // deleted_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the User exists in the database.
func (u *User) Exists() bool {
	return u._exists
}

// SetExists determines if the User exists in the database.
func (u *User) SetExists(exists bool) {
	u._exists = exists
}

// Deleted provides information if the User has been deleted from the database.
func (u *User) Deleted() bool {
	return u._deleted
}

// Insert inserts the User to the database.
func (u *User) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if u._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.users (
name, email, password, email_verified_at, created_at, updated_at, deleted_at
) VALUES (
$1, $2, $3, $4, $5, $6, $7
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, u.Name, u.Email, u.Password, u.EmailVerifiedAt, u.CreatedAt, u.UpdatedAt, u.DeletedAt).Scan(&u.ID)

	db.WriteLog(sqlstr, time.Since(start), u.Name, u.Email, u.Password, u.EmailVerifiedAt, u.CreatedAt, u.UpdatedAt, u.DeletedAt)

	if err != nil {
		return err
	}

	// set existence
	u._exists = true

	return nil
}

// Update updates the User in the database.
func (u *User) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !u._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if u._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.users SET (
name, email, password, email_verified_at, created_at, updated_at, deleted_at
) = (
$1, $2, $3, $4, $5, $6, $7
) WHERE id = $8
`

	// run query
	_, err = db.Exec(ctx, sqlstr, u.Name, u.Email, u.Password, u.EmailVerifiedAt, u.CreatedAt, u.UpdatedAt, u.DeletedAt, u.ID)

	db.WriteLog(sqlstr, time.Since(start), u.Name, u.Email, u.Password, u.EmailVerifiedAt, u.CreatedAt, u.UpdatedAt, u.DeletedAt, u.ID)

	return err
}

// Save saves the User to the database.
func (u *User) Save(db pgxdb.DBQuery) error {
	if u.Exists() {
		return u.Update(db)
	}

	return u.Insert(db)
}

// Upsert performs an upsert for User.
//
// NOTE: PostgreSQL 9.5+ only
func (u *User) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if u._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.users (
id, name, email, password, email_verified_at, created_at, updated_at, deleted_at
) VALUES (
$1, $2, $3, $4, $5, $6, $7, $8
) ON CONFLICT (id) DO UPDATE SET (
id, name, email, password, email_verified_at, created_at, updated_at, deleted_at
) = (
EXCLUDED.id, EXCLUDED.name, EXCLUDED.email, EXCLUDED.password, EXCLUDED.email_verified_at, EXCLUDED.created_at, EXCLUDED.updated_at, EXCLUDED.deleted_at
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, u.ID, u.Name, u.Email, u.Password, u.EmailVerifiedAt, u.CreatedAt, u.UpdatedAt, u.DeletedAt)

	db.WriteLog(sqlstr, time.Since(start), u.ID, u.Name, u.Email, u.Password, u.EmailVerifiedAt, u.CreatedAt, u.UpdatedAt, u.DeletedAt)

	if err != nil {
		return err
	}

	// set existence
	u._exists = true

	return nil
}

// Delete deletes the User from the database.
func (u *User) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !u._exists {
		return nil
	}

	// if deleted, bail
	if u._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.users
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, u.ID)

	db.WriteLog(sqlstr, time.Since(start), u.ID)

	if err != nil {
		return err
	}

	// set deleted
	u._deleted = true

	return nil
}

// GetAllUser returns all rows from 'public.users',
func GetAllUser(db pgxdb.DBQuery) ([]*User, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, email, password, email_verified_at, created_at, updated_at, deleted_at
FROM public.users
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*User
	for q.Next() {
		u := User{}

		// scan
		err = q.Scan(&u.ID, &u.Name, &u.Email, &u.Password, &u.EmailVerifiedAt, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt)
		if err != nil {
			return nil, err
		}
		u.SetExists(true)

		res = append(res, &u)
	}

	return res, nil
}

// GetAllUserWithPagination returns a paginated set of rows from 'public.users',
func GetAllUserWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*User, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, email, password, email_verified_at, created_at, updated_at, deleted_at
FROM public.users
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*User
	for q.Next() {
		u := User{}

		// scan
		err = q.Scan(&u.ID, &u.Name, &u.Email, &u.Password, &u.EmailVerifiedAt, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt)
		if err != nil {
			return nil, err
		}
		u.SetExists(true)

		res = append(res, &u)
	}

	return res, nil
}

// GetUsersBySQL returns rows from 'public.users' by your SQL,
func GetUsersBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*User, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*User
	for q.Next() {
		u := User{}

		// scan
		err = q.Scan(&u.ID, &u.Name, &u.Email, &u.Password, &u.EmailVerifiedAt, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &u)
	}

	return res, nil
}

// GetUsersBySQLWithPagination returns a paginated set of rows from 'public.users' by your SQL,
func GetUsersBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*User, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*User
	for q.Next() {
		u := User{}

		// scan
		err = q.Scan(&u.ID, &u.Name, &u.Email, &u.Password, &u.EmailVerifiedAt, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &u)
	}

	return res, nil
}

// GetLastUser returns last row from 'public.users',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDUser(db pgxdb.DBQuery) (*User, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, email, password, email_verified_at, created_at, updated_at, deleted_at
FROM public.users
ORDER BY
id DESC
LIMIT 1
`

	var u User
	err := db.QueryRow(ctx, sqlstr).Scan(&u.ID, &u.Name, &u.Email, &u.Password, &u.EmailVerifiedAt, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	u._exists = true
	u._deleted = false

	return &u, nil
}

// UserByEmail retrieves a row from 'public.users' as a User.
//
// Generated from index 'users_email_uindex'.
func GetUserByEmail(db pgxdb.DBQuery, email string) (*User, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, name, email, password, email_verified_at, created_at, updated_at, deleted_at
FROM
	public.users
WHERE
	email = $1
`

	// run query
	u := User{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, email).Scan(&u.ID, &u.Name, &u.Email, &u.Password, &u.EmailVerifiedAt, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt)

	db.WriteLog(sqlstr, time.Since(start), email)

	if err != nil {
		return nil, err
	}

	return &u, nil
}

// ----- Index Methods for User -----

// UserByID retrieves a row from 'public.users' as a User.
//
// Generated from index 'users_pk'.
func GetUserByID(db pgxdb.DBQuery, id int64) (*User, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, name, email, password, email_verified_at, created_at, updated_at, deleted_at
FROM
	public.users
WHERE
	id = $1
`

	// run query
	u := User{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&u.ID, &u.Name, &u.Email, &u.Password, &u.EmailVerifiedAt, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &u, nil
}

// ----- Index Methods for User -----

// GetActiveUserByEmail runs a custom query, returning results as User.
func GetActiveUserByEmail(db pgxdb.DBQuery, email string) (*User, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	var sqlstr = `SELECT ` + "\n" +
		`id, name, email, password, email_verified_at, created_at, updated_at, deleted_at ` + "\n" +
		`FROM ` + "\n" +
		`public.users ` + "\n" +
		`WHERE ` + "\n" +
		`email = $1 ` + "\n" +
		`AND deleted_at IS NULL`

	// run query
	var u User
	err = db.QueryRow(ctx, sqlstr, email).Scan(&u.ID, &u.Name, &u.Email, &u.Password, &u.EmailVerifiedAt, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt)

	db.WriteLog(sqlstr, time.Since(start), email)

	if err != nil {
		return nil, err
	}

	u._exists = true
	u._deleted = false

	return &u, nil
}
