// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/lib/pq"
	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// UserWithRole represents a row from 'public.user_with_roles'.
type UserWithRole struct {
	ID              sql.NullInt64  `json:"id"`                // id
	Name            sql.NullString `json:"name"`              // name
	Email           sql.NullString `json:"email"`             // email
	Password        sql.NullString `json:"password"`          // password
	EmailVerifiedAt pq.NullTime    `json:"email_verified_at"` // email_verified_at
	CreatedAt       pq.NullTime    `json:"created_at"`        // created_at
	UpdatedAt       pq.NullTime    `json:"updated_at"`        // updated_at
	DeletedAt       pq.NullTime    `json:"deleted_at"`        // deleted_at
	Roles           sql.NullString `json:"roles"`             // roles
}

// GetAllUserWithRole returns all rows from 'public.user_with_roles',
func GetAllUserWithRole(db pgxdb.DBQuery) ([]*UserWithRole, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, email, password, email_verified_at, created_at, updated_at, deleted_at, roles
FROM public.user_with_roles
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UserWithRole
	for q.Next() {
		uwr := UserWithRole{}

		// scan
		err = q.Scan(&uwr.ID, &uwr.Name, &uwr.Email, &uwr.Password, &uwr.EmailVerifiedAt, &uwr.CreatedAt, &uwr.UpdatedAt, &uwr.DeletedAt, &uwr.Roles)
		if err != nil {
			return nil, err
		}

		res = append(res, &uwr)
	}

	return res, nil
}

// GetAllUserWithRoleWithPagination returns a paginated set of rows from 'public.user_with_roles',
func GetAllUserWithRoleWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*UserWithRole, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, email, password, email_verified_at, created_at, updated_at, deleted_at, roles
FROM public.user_with_roles
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UserWithRole
	for q.Next() {
		uwr := UserWithRole{}

		// scan
		err = q.Scan(&uwr.ID, &uwr.Name, &uwr.Email, &uwr.Password, &uwr.EmailVerifiedAt, &uwr.CreatedAt, &uwr.UpdatedAt, &uwr.DeletedAt, &uwr.Roles)
		if err != nil {
			return nil, err
		}

		res = append(res, &uwr)
	}

	return res, nil
}

// GetAllUserWithRoleCount returns count of all rows from 'public.user_with_roles',
func GetAllUserWithRoleCount(db pgxdb.DBQuery) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `SELECT COUNT(*) FROM public.user_with_roles`

	var count int64
	err := db.QueryRow(ctx, sqlstr).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetUserWithRolesBySQL returns rows from 'public.user_with_roles' by your SQL,
func GetUserWithRolesBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*UserWithRole, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UserWithRole
	for q.Next() {
		uwr := UserWithRole{}

		// scan
		err = q.Scan(&uwr.ID, &uwr.Name, &uwr.Email, &uwr.Password, &uwr.EmailVerifiedAt, &uwr.CreatedAt, &uwr.UpdatedAt, &uwr.DeletedAt, &uwr.Roles)
		if err != nil {
			return nil, err
		}

		res = append(res, &uwr)
	}

	return res, nil
}

// GetUserWithRolesBySQLWithPagination returns a paginated set of rows from 'public.user_with_roles' by your SQL,
func GetUserWithRolesBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*UserWithRole, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UserWithRole
	for q.Next() {
		uwr := UserWithRole{}

		// scan
		err = q.Scan(&uwr.ID, &uwr.Name, &uwr.Email, &uwr.Password, &uwr.EmailVerifiedAt, &uwr.CreatedAt, &uwr.UpdatedAt, &uwr.DeletedAt, &uwr.Roles)
		if err != nil {
			return nil, err
		}

		res = append(res, &uwr)
	}

	return res, nil
}

// GetUserWithRolesBySQLCount returns count of rows from 'public.user_with_roles' by your SQL,
func GetUserWithRolesBySQLCount(db pgxdb.DBQuery, sqlstr string, args ...any) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	var count int64
	err := db.QueryRow(ctx, countSQL, args...).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), args...)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetLastUserWithRole returns last row from 'public.user_with_roles',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDUserWithRole(db pgxdb.DBQuery) (*UserWithRole, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, name, email, password, email_verified_at, created_at, updated_at, deleted_at, roles
FROM public.user_with_roles
ORDER BY
id DESC
LIMIT 1
`

	var uwr UserWithRole
	err := db.QueryRow(ctx, sqlstr).Scan(&uwr.ID, &uwr.Name, &uwr.Email, &uwr.Password, &uwr.EmailVerifiedAt, &uwr.CreatedAt, &uwr.UpdatedAt, &uwr.DeletedAt, &uwr.Roles)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}

	return &uwr, nil
}
