// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"errors"
	"fmt"
	"time"

	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// UsersSetting represents a row from 'public.users_settings'.
type UsersSetting struct {
	ID         int64 `json:"id"`          // id
	UserID     int64 `json:"user_id"`     // user_id
	SettingsID int64 `json:"settings_id"` // settings_id
	Value      JSON  `json:"value"`       // value

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the UsersSetting exists in the database.
func (us *UsersSetting) Exists() bool {
	return us._exists
}

// SetExists determines if the UsersSetting exists in the database.
func (us *UsersSetting) SetExists(exists bool) {
	us._exists = exists
}

// Deleted provides information if the UsersSetting has been deleted from the database.
func (us *UsersSetting) Deleted() bool {
	return us._deleted
}

// Insert inserts the UsersSetting to the database.
func (us *UsersSetting) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if us._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.users_settings (
user_id, settings_id, value
) VALUES (
$1, $2, $3
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, us.UserID, us.SettingsID, us.Value).Scan(&us.ID)

	db.WriteLog(sqlstr, time.Since(start), us.UserID, us.SettingsID, us.Value)

	if err != nil {
		return err
	}

	// set existence
	us._exists = true

	return nil
}

// Update updates the UsersSetting in the database.
func (us *UsersSetting) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !us._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if us._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.users_settings SET (
user_id, settings_id, value
) = (
$1, $2, $3
) WHERE id = $4
`

	// run query
	_, err = db.Exec(ctx, sqlstr, us.UserID, us.SettingsID, us.Value, us.ID)

	db.WriteLog(sqlstr, time.Since(start), us.UserID, us.SettingsID, us.Value, us.ID)

	return err
}

// Save saves the UsersSetting to the database.
func (us *UsersSetting) Save(db pgxdb.DBQuery) error {
	if us.Exists() {
		return us.Update(db)
	}

	return us.Insert(db)
}

// Upsert performs an upsert for UsersSetting.
//
// NOTE: PostgreSQL 9.5+ only
func (us *UsersSetting) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if us._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.users_settings (
id, user_id, settings_id, value
) VALUES (
$1, $2, $3, $4
) ON CONFLICT (id) DO UPDATE SET (
id, user_id, settings_id, value
) = (
EXCLUDED.id, EXCLUDED.user_id, EXCLUDED.settings_id, EXCLUDED.value
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, us.ID, us.UserID, us.SettingsID, us.Value)

	db.WriteLog(sqlstr, time.Since(start), us.ID, us.UserID, us.SettingsID, us.Value)

	if err != nil {
		return err
	}

	// set existence
	us._exists = true

	return nil
}

// Delete deletes the UsersSetting from the database.
func (us *UsersSetting) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !us._exists {
		return nil
	}

	// if deleted, bail
	if us._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.users_settings
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, us.ID)

	db.WriteLog(sqlstr, time.Since(start), us.ID)

	if err != nil {
		return err
	}

	// set deleted
	us._deleted = true

	return nil
}

// GetAllUsersSetting returns all rows from 'public.users_settings',
func GetAllUsersSetting(db pgxdb.DBQuery) ([]*UsersSetting, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, user_id, settings_id, value
FROM public.users_settings
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UsersSetting
	for q.Next() {
		us := UsersSetting{}

		// scan
		err = q.Scan(&us.ID, &us.UserID, &us.SettingsID, &us.Value)
		if err != nil {
			return nil, err
		}
		us.SetExists(true)

		res = append(res, &us)
	}

	return res, nil
}

// GetAllUsersSettingWithPagination returns a paginated set of rows from 'public.users_settings',
func GetAllUsersSettingWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*UsersSetting, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, user_id, settings_id, value
FROM public.users_settings
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UsersSetting
	for q.Next() {
		us := UsersSetting{}

		// scan
		err = q.Scan(&us.ID, &us.UserID, &us.SettingsID, &us.Value)
		if err != nil {
			return nil, err
		}
		us.SetExists(true)

		res = append(res, &us)
	}

	return res, nil
}

// GetAllUsersSettingCount returns count of all rows from 'public.users_settings',
func GetAllUsersSettingCount(db pgxdb.DBQuery) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `SELECT COUNT(*) FROM public.users_settings`

	var count int64
	err := db.QueryRow(ctx, sqlstr).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetUsersSettingsBySQL returns rows from 'public.users_settings' by your SQL,
func GetUsersSettingsBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*UsersSetting, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UsersSetting
	for q.Next() {
		us := UsersSetting{}

		// scan
		err = q.Scan(&us.ID, &us.UserID, &us.SettingsID, &us.Value)
		if err != nil {
			return nil, err
		}

		res = append(res, &us)
	}

	return res, nil
}

// GetUsersSettingsBySQLWithPagination returns a paginated set of rows from 'public.users_settings' by your SQL,
func GetUsersSettingsBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*UsersSetting, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UsersSetting
	for q.Next() {
		us := UsersSetting{}

		// scan
		err = q.Scan(&us.ID, &us.UserID, &us.SettingsID, &us.Value)
		if err != nil {
			return nil, err
		}

		res = append(res, &us)
	}

	return res, nil
}

// GetUsersSettingsBySQLCount returns count of rows from 'public.users_settings' by your SQL,
func GetUsersSettingsBySQLCount(db pgxdb.DBQuery, sqlstr string, args ...any) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	var count int64
	err := db.QueryRow(ctx, countSQL, args...).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), args...)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetLastUsersSetting returns last row from 'public.users_settings',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDUsersSetting(db pgxdb.DBQuery) (*UsersSetting, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, user_id, settings_id, value
FROM public.users_settings
ORDER BY
id DESC
LIMIT 1
`

	var us UsersSetting
	err := db.QueryRow(ctx, sqlstr).Scan(&us.ID, &us.UserID, &us.SettingsID, &us.Value)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	us._exists = true
	us._deleted = false

	return &us, nil
}

// User returns the User associated with the UsersSetting's UserID (user_id).
//
// Generated from foreign key 'users_settings_users_id_fk'.
func (us *UsersSetting) GetUser(db pgxdb.DBQuery) (*User, error) {
	return GetUserByID(db, us.UserID)
}

// UsersSettingByID retrieves a row from 'public.users_settings' as a UsersSetting.
//
// Generated from index 'users_settings_pk'.
func GetUsersSettingByID(db pgxdb.DBQuery, id int64) (*UsersSetting, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, user_id, settings_id, value
FROM
	public.users_settings
WHERE
	id = $1
`

	// run query
	us := UsersSetting{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&us.ID, &us.UserID, &us.SettingsID, &us.Value)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &us, nil
}

// GetUsersSettingByIDCount retrieves count of rows from 'public.users_settings' by index 'users_settings_pk'.
func GetUsersSettingByIDCount(db pgxdb.DBQuery, id int64) (int64, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	COUNT(*)
FROM
	public.users_settings
WHERE
	id = $1
`

	// run query
	var count int64
	err = db.QueryRow(ctx, sqlstr, id).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// ----- Index Methods for UsersSetting -----

// UsersSettingByUserIDSettingsID retrieves a row from 'public.users_settings' as a UsersSetting.
//
// Generated from index 'users_settings_user_id_settings_id_idx'.
func GetUsersSettingByUserIDSettingsID(db pgxdb.DBQuery, userID int64, settingsID int64) (*UsersSetting, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, user_id, settings_id, value
FROM
	public.users_settings
WHERE
	user_id = $1 AND settings_id = $2
`

	// run query
	us := UsersSetting{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, userID, settingsID).Scan(&us.ID, &us.UserID, &us.SettingsID, &us.Value)

	db.WriteLog(sqlstr, time.Since(start), userID, settingsID)

	if err != nil {
		return nil, err
	}

	return &us, nil
}

// GetUsersSettingByUserIDSettingsIDCount retrieves count of rows from 'public.users_settings' by index 'users_settings_user_id_settings_id_idx'.
func GetUsersSettingByUserIDSettingsIDCount(db pgxdb.DBQuery, userID int64, settingsID int64) (int64, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	COUNT(*)
FROM
	public.users_settings
WHERE
	user_id = $1 AND settings_id = $2
`

	// run query
	var count int64
	err = db.QueryRow(ctx, sqlstr, userID, settingsID).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start), userID, settingsID)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// ----- Index Methods for UsersSetting -----
