// Package goxus contains the types for schema 'public'.
package goxus

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/lib/pq"
	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

// UsersToken represents a row from 'public.users_tokens'.
type UsersToken struct {
	ID         int64       `json:"id"`           // id
	Token      string      `json:"token"`        // token
	UserID     int64       `json:"user_id"`      // user_id
	LastUsedAt pq.NullTime `json:"last_used_at"` // last_used_at
	CreatedAt  time.Time   `json:"created_at"`   // created_at
	UpdatedAt  time.Time   `json:"updated_at"`   // updated_at
	DeletedAt  pq.NullTime `json:"deleted_at"`   // deleted_at

	// @crud
	// xo fields
	_exists, _deleted bool
	// @end-crud

}

// @crud
// Exists determines if the UsersToken exists in the database.
func (ut *UsersToken) Exists() bool {
	return ut._exists
}

// SetExists determines if the UsersToken exists in the database.
func (ut *UsersToken) SetExists(exists bool) {
	ut._exists = exists
}

// Deleted provides information if the UsersToken has been deleted from the database.
func (ut *UsersToken) Deleted() bool {
	return ut._deleted
}

// @end-crud

// @crud
// Insert inserts the UsersToken to the database.
func (ut *UsersToken) Insert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if ut._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	// language=SQL
	const sqlstr = `
INSERT INTO public.users_tokens (
token, user_id, last_used_at, created_at, updated_at, deleted_at
) VALUES (
$1, $2, $3, $4, $5, $6
) RETURNING id
`

	// run query
	err = db.QueryRow(ctx, sqlstr, ut.Token, ut.UserID, ut.LastUsedAt, ut.CreatedAt, ut.UpdatedAt, ut.DeletedAt).Scan(&ut.ID)

	db.WriteLog(sqlstr, time.Since(start), ut.Token, ut.UserID, ut.LastUsedAt, ut.CreatedAt, ut.UpdatedAt, ut.DeletedAt)

	if err != nil {
		return err
	}

	// set existence
	ut._exists = true

	return nil
}

// @end-crud

// @crud

// Update updates the UsersToken in the database.
func (ut *UsersToken) Update(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !ut._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if ut._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	// language=SQL
	const sqlstr = `
UPDATE public.users_tokens SET (
token, user_id, last_used_at, created_at, updated_at, deleted_at
) = (
$1, $2, $3, $4, $5, $6
) WHERE id = $7
`

	// run query
	_, err = db.Exec(ctx, sqlstr, ut.Token, ut.UserID, ut.LastUsedAt, ut.CreatedAt, ut.UpdatedAt, ut.DeletedAt, ut.ID)

	db.WriteLog(sqlstr, time.Since(start), ut.Token, ut.UserID, ut.LastUsedAt, ut.CreatedAt, ut.UpdatedAt, ut.DeletedAt, ut.ID)

	return err
}

// Save saves the UsersToken to the database.
func (ut *UsersToken) Save(db pgxdb.DBQuery) error {
	if ut.Exists() {
		return ut.Update(db)
	}

	return ut.Insert(db)
}

// Upsert performs an upsert for UsersToken.
//
// NOTE: PostgreSQL 9.5+ only
func (ut *UsersToken) Upsert(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if already exist, bail
	if ut._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	// language=SQL
	const sqlstr = `
INSERT INTO public.users_tokens (
id, token, user_id, last_used_at, created_at, updated_at, deleted_at
) VALUES (
$1, $2, $3, $4, $5, $6, $7
) ON CONFLICT (id) DO UPDATE SET (
id, token, user_id, last_used_at, created_at, updated_at, deleted_at
) = (
EXCLUDED.id, EXCLUDED.token, EXCLUDED.user_id, EXCLUDED.last_used_at, EXCLUDED.created_at, EXCLUDED.updated_at, EXCLUDED.deleted_at
)
`

	// run query
	_, err = db.Exec(ctx, sqlstr, ut.ID, ut.Token, ut.UserID, ut.LastUsedAt, ut.CreatedAt, ut.UpdatedAt, ut.DeletedAt)

	db.WriteLog(sqlstr, time.Since(start), ut.ID, ut.Token, ut.UserID, ut.LastUsedAt, ut.CreatedAt, ut.UpdatedAt, ut.DeletedAt)

	if err != nil {
		return err
	}

	// set existence
	ut._exists = true

	return nil
}

// @end-crud

// @crud
// Delete deletes the UsersToken from the database.
func (ut *UsersToken) Delete(db pgxdb.DBQuery) error {
	var err error

	start := time.Now()

	ctx := context.Background()

	// if doesn't exist, bail
	if !ut._exists {
		return nil
	}

	// if deleted, bail
	if ut._deleted {
		return nil
	}

	// sql query
	// language=SQL
	const sqlstr = `
DELETE FROM public.users_tokens
WHERE id = $1
`

	// run query
	_, err = db.Exec(ctx, sqlstr, ut.ID)

	db.WriteLog(sqlstr, time.Since(start), ut.ID)

	if err != nil {
		return err
	}

	// set deleted
	ut._deleted = true

	return nil
}

// @end-crud

// GetAllUsersToken returns all rows from 'public.users_tokens',
func GetAllUsersToken(db pgxdb.DBQuery) ([]*UsersToken, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, token, user_id, last_used_at, created_at, updated_at, deleted_at
FROM public.users_tokens
ORDER BY
	id ASC
`

	q, err := db.Query(ctx, sqlstr)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UsersToken
	for q.Next() {
		ut := UsersToken{}

		// scan
		err = q.Scan(&ut.ID, &ut.Token, &ut.UserID, &ut.LastUsedAt, &ut.CreatedAt, &ut.UpdatedAt, &ut.DeletedAt)
		if err != nil {
			return nil, err
		}
		// @crud
		ut.SetExists(true)
		// @end-crud

		res = append(res, &ut)
	}

	return res, nil
}

// GetAllUsersTokenWithPagination returns a paginated set of rows from 'public.users_tokens',
func GetAllUsersTokenWithPagination(db pgxdb.DBQuery, limit, offset int) ([]*UsersToken, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, token, user_id, last_used_at, created_at, updated_at, deleted_at
FROM public.users_tokens
ORDER BY
	id ASC
LIMIT $1 OFFSET $2
`

	q, err := db.Query(ctx, sqlstr, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UsersToken
	for q.Next() {
		ut := UsersToken{}

		// scan
		err = q.Scan(&ut.ID, &ut.Token, &ut.UserID, &ut.LastUsedAt, &ut.CreatedAt, &ut.UpdatedAt, &ut.DeletedAt)
		if err != nil {
			return nil, err
		}
		// @crud
		ut.SetExists(true)
		// @end-crud

		res = append(res, &ut)
	}

	return res, nil
}

// GetAllUsersTokenCount returns count of all rows from 'public.users_tokens',
func GetAllUsersTokenCount(db pgxdb.DBQuery) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `SELECT COUNT(*) FROM public.users_tokens`

	var count int64
	err := db.QueryRow(ctx, sqlstr).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetUsersTokensBySQL returns rows from 'public.users_tokens' by your SQL,
func GetUsersTokensBySQL(db pgxdb.DBQuery, sqlstr string, args ...any) ([]*UsersToken, error) {
	ctx := context.Background()

	start := time.Now()

	q, err := db.Query(ctx, sqlstr, args...)

	db.WriteLog(sqlstr, time.Since(start), args...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UsersToken
	for q.Next() {
		ut := UsersToken{}

		// scan
		err = q.Scan(&ut.ID, &ut.Token, &ut.UserID, &ut.LastUsedAt, &ut.CreatedAt, &ut.UpdatedAt, &ut.DeletedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &ut)
	}

	return res, nil
}

// GetUsersTokensBySQLWithPagination returns a paginated set of rows from 'public.users_tokens' by your SQL,
func GetUsersTokensBySQLWithPagination(db pgxdb.DBQuery, sqlstr string, limit, offset int, args ...any) ([]*UsersToken, error) {
	ctx := context.Background()

	start := time.Now()

	paginatedSQL := sqlstr + fmt.Sprintf("\nLIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	paginatedArgs := append(args, limit, offset)

	q, err := db.Query(ctx, paginatedSQL, paginatedArgs...)

	db.WriteLog(paginatedSQL, time.Since(start), paginatedArgs...)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	var res []*UsersToken
	for q.Next() {
		ut := UsersToken{}

		// scan
		err = q.Scan(&ut.ID, &ut.Token, &ut.UserID, &ut.LastUsedAt, &ut.CreatedAt, &ut.UpdatedAt, &ut.DeletedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &ut)
	}

	return res, nil
}

// GetUsersTokensBySQLCount returns count of rows from 'public.users_tokens' by your SQL,
func GetUsersTokensBySQLCount(db pgxdb.DBQuery, sqlstr string, args ...any) (int64, error) {
	ctx := context.Background()

	start := time.Now()

	countSQL := `SELECT COUNT(*) FROM (` + sqlstr + `) AS count_query`

	var count int64
	err := db.QueryRow(ctx, countSQL, args...).Scan(&count)

	db.WriteLog(countSQL, time.Since(start), args...)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// GetLastUsersToken returns last row from 'public.users_tokens',
//
// errors possible
//  1. pgx.ErrNoRows
//  2. pgconn.PgError
func GetLastIDUsersToken(db pgxdb.DBQuery) (*UsersToken, error) {
	ctx := context.Background()

	start := time.Now()

	// language=SQL
	const sqlstr = `
SELECT
id, token, user_id, last_used_at, created_at, updated_at, deleted_at
FROM public.users_tokens
ORDER BY
id DESC
LIMIT 1
`

	var ut UsersToken
	err := db.QueryRow(ctx, sqlstr).Scan(&ut.ID, &ut.Token, &ut.UserID, &ut.LastUsedAt, &ut.CreatedAt, &ut.UpdatedAt, &ut.DeletedAt)

	db.WriteLog(sqlstr, time.Since(start))

	if err != nil {
		return nil, err
	}
	// @crud
	ut._exists = true
	ut._deleted = false
	// @end-crud

	return &ut, nil
}

// User returns the User associated with the UsersToken's UserID (user_id).
//
// Generated from foreign key 'users_tokens_users_fk'.
func (ut *UsersToken) GetUser(db pgxdb.DBQuery) (*User, error) {
	return GetUserByID(db, ut.UserID)
}

// UsersTokenByID retrieves a row from 'public.users_tokens' as a UsersToken.
//
// Generated from index 'users_tokens_pk'.
func GetUsersTokenByID(db pgxdb.DBQuery, id int64) (*UsersToken, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, token, user_id, last_used_at, created_at, updated_at, deleted_at
FROM
	public.users_tokens
WHERE
	id = $1
`

	// run query
	ut := UsersToken{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, id).Scan(&ut.ID, &ut.Token, &ut.UserID, &ut.LastUsedAt, &ut.CreatedAt, &ut.UpdatedAt, &ut.DeletedAt)

	db.WriteLog(sqlstr, time.Since(start), id)

	if err != nil {
		return nil, err
	}

	return &ut, nil
}

// ----- Index Methods for UsersToken -----

// UsersTokenByToken retrieves a row from 'public.users_tokens' as a UsersToken.
//
// Generated from index 'users_tokens_token_uindex'.
func GetUsersTokenByToken(db pgxdb.DBQuery, token string) (*UsersToken, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, token, user_id, last_used_at, created_at, updated_at, deleted_at
FROM
	public.users_tokens
WHERE
	token = $1
`

	// run query
	ut := UsersToken{
		_exists: true,
	}

	err = db.QueryRow(ctx, sqlstr, token).Scan(&ut.ID, &ut.Token, &ut.UserID, &ut.LastUsedAt, &ut.CreatedAt, &ut.UpdatedAt, &ut.DeletedAt)

	db.WriteLog(sqlstr, time.Since(start), token)

	if err != nil {
		return nil, err
	}

	return &ut, nil
}

// ----- Index Methods for UsersToken -----

// UsersTokensByUserID retrieves a row from 'public.users_tokens' as a UsersToken.
//
// Generated from index 'users_tokens_user_id_index'.
func GetUsersTokensByUserID(db pgxdb.DBQuery, userID int64) ([]*UsersToken, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	id, token, user_id, last_used_at, created_at, updated_at, deleted_at
FROM
	public.users_tokens
WHERE
	user_id = $1
`

	// run query
	q, err := db.Query(ctx, sqlstr, userID)

	db.WriteLog(sqlstr, time.Since(start), userID)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*UsersToken{}
	for q.Next() {
		ut := UsersToken{
			_exists: true,
		}

		// scan
		err = q.Scan(&ut.ID, &ut.Token, &ut.UserID, &ut.LastUsedAt, &ut.CreatedAt, &ut.UpdatedAt, &ut.DeletedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &ut)
	}

	return res, nil
}

// GetUsersTokensByUserIDWithPagination retrieves a paginated set of rows from 'public.users_tokens' as a UsersToken.
//
// Generated from index 'users_tokens_user_id_index'.
func GetUsersTokensByUserIDWithPagination(db pgxdb.DBQuery, userID int64, limit, offset int) ([]*UsersToken, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	var sqlstr string
	{
		const baseSQL = `
SELECT
	id, token, user_id, last_used_at, created_at, updated_at, deleted_at
FROM
	public.users_tokens
WHERE
	user_id = $1
ORDER BY
	id ASC
`
		sqlstr = baseSQL + "\nLIMIT $" + fmt.Sprint(1+1) + " OFFSET $" + fmt.Sprint(2+1)
	}

	// run query
	q, err := db.Query(ctx, sqlstr, userID, limit, offset)

	db.WriteLog(sqlstr, time.Since(start), userID, limit, offset)

	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*UsersToken{}
	for q.Next() {
		ut := UsersToken{
			_exists: true,
		}

		// scan
		err = q.Scan(&ut.ID, &ut.Token, &ut.UserID, &ut.LastUsedAt, &ut.CreatedAt, &ut.UpdatedAt, &ut.DeletedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &ut)
	}

	return res, nil
}

// GetUsersTokensByUserIDCount retrieves count of rows from 'public.users_tokens' by index 'users_tokens_user_id_index'.
func GetUsersTokensByUserIDCount(db pgxdb.DBQuery, userID int64) (int64, error) {
	var err error

	start := time.Now()

	ctx := context.Background()

	// sql query
	// language=SQL
	const sqlstr = `
SELECT
	COUNT(*)
FROM
	public.users_tokens
WHERE
	user_id = $1
`

	// run query
	var count int64
	err = db.QueryRow(ctx, sqlstr, userID).Scan(&count)

	db.WriteLog(sqlstr, time.Since(start), userID)

	if err != nil {
		return 0, err
	}

	return count, nil
}

// ----- Index Methods for UsersToken -----
