// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"goxus/src/internal/app/goxus/api/server"
	"goxus/src/internal/app/goxus/cli"
	"goxus/src/internal/app/goxus/config"
	"goxus/src/internal/app/goxus/cron-job/jobs/example"
	"goxus/src/internal/app/goxus/domain"
	"goxus/src/internal/app/goxus/log"
)

// Injectors from wire.go:

// initializeApp is the Wire injector entrypoint. It aggregates all ProviderSets
// and constructs the top-level application. No logic belongs here.
func initializeApp() (IApp, func(), error) {
	service, cleanup, err := cli.ProvideCLI()
	if err != nil {
		return nil, nil, err
	}
	configappService, cleanup2, err := configapp.ProvideConfigApp(service)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	domainService, cleanup3, err := domainapp.ProvideDomain(service, configappService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iLogFile, cleanup4, err := logfile.ProvideLogFile(service)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ihttpServer, cleanup5, err := server.ProvideAPI(configappService, iLogFile, domainService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cron, cleanup6, err := examplejobs.ProvideExampleJobs(domainService)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iApp, cleanup7, err := newApp(service, domainService, ihttpServer, cron)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return iApp, func() {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
