// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"goxus/src/internal/app/goxus/api/server"
	"goxus/src/internal/app/goxus/cli"
	"goxus/src/internal/app/goxus/config"
	"goxus/src/internal/app/goxus/cron-job/jobs"
	"goxus/src/internal/app/goxus/cron-job/jobs/example"
	"goxus/src/internal/app/goxus/cron-job/jobs/token-cleanup"
	"goxus/src/internal/app/goxus/domain"
	"goxus/src/internal/app/goxus/domain/user"
	"goxus/src/internal/app/goxus/log"
	"goxus/src/internal/pkg/db/goxus"
	"goxus/src/internal/pkg/services/ratelimit"
	"goxus/src/internal/pkg/services/rbac"
)

// Injectors from wire.go:

// initializeApp is the Wire injector entrypoint. It aggregates all ProviderSets
// and constructs the top-level application. No logic belongs here.
func initializeApp() (IApp, func(), error) {
	service, cleanup, err := cli.ProvideCLI()
	if err != nil {
		return nil, nil, err
	}
	configappService, cleanup2, err := configapp.ProvideConfigApp(service)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	config, err := configapp.ProvideDBConfig(configappService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sqlLoggerFunc, cleanup3, err := logfile.ProvideSQLLogger(configappService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dbGoxusRepo, cleanup4, err := goxus.ProviderGoxus(config, sqlLoggerFunc)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rbacService, cleanup5, err := rbac.ProvideRbac(dbGoxusRepo)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userdomainService, cleanup6, err := userdomain.ProvideUserService(dbGoxusRepo, rbacService, configappService)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	domainService, cleanup7, err := domainapp.ProvideDomain(service, configappService, rbacService, userdomainService)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iLogFile, cleanup8, err := logfile.ProvideLogFile(service)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ratelimitService, cleanup9, err := ratelimit.ProvideRateLimiter(configappService)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ihttpServer, cleanup10, err := server.ProvideAPI(configappService, iLogFile, domainService, ratelimitService)
	if err != nil {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	job, cleanup11, err := examplejobs.ProvideExampleJob(configappService, domainService)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tokencleanupJob, cleanup12, err := tokencleanup.ProvideTokenCleanupJob(configappService, domainService)
	if err != nil {
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cron, cleanup13, err := cronjobs.ProvideCronScheduler(job, tokencleanupJob, configappService)
	if err != nil {
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iApp, cleanup14, err := newApp(service, domainService, ihttpServer, cron)
	if err != nil {
		cleanup13()
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return iApp, func() {
		cleanup14()
		cleanup13()
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
